### ISSUE TITLE
ZXCapture issue with start/stop methods

### ISSUE THREAD

**Issue by rmaddy** [TheLevelUp/ZXingObjC#163]
There is a problem with the `start` and `stop` methods of the `ZXCapture` class. Basically, the `stop` method removes `self.layer` from its super layer but the `start` method doesn't put it back.

This means that once the `stop` method is called, the `ZXCapture` instance can't be started again by calling the `start` method.

**Comment by cwalcott** [comment]
Agreed that this was weird. `ZXCapture` came from the original ZXing and definitely has some issues. 1d7eb88 stops removing the layer in `stop`.
