### ISSUE TITLE
Linker problems

### ISSUE THREAD

**Issue by rlissner** [TheLevelUp/ZXingObjC#165]
Can anyone tell me why this is happening:

Undefined symbols for architecture armv7:
  "_OBJC_CLASS_$_ZXDecodeHints", referenced from:
      objc-class-ref in S2VC4.o
  "_OBJC_CLASS_$_ZXCapture", referenced from:
      objc-class-ref in S2VC4.o
ld: symbol(s) not found for architecture armv7
clang: error: linker command failed with exit code 1 (use -v to see invocation)

Environment: 
Xcode5
Device is my 5S, attached to mac.
Architectures:  Standard (in my code and in pods)
Build active architecture only:  NO
Valid Architectures:  arm64, armv7 armv7s
Profile:  team provisioning provide
ZXing downloaded about a week ago.

**Comment by cwalcott** [comment]
This is probably a configuration issue: http://stackoverflow.com/a/6429568
