### ISSUE TITLE
ZXCapture fails to initialize capture if it has no delegate

### ISSUE THREAD

**Issue by Vadim-Yelagin** [TheLevelUp/ZXingObjC#169]
ZXCapture has some weird logic in its start, startStop and setDelegate methods that depends on whether the delegate is nil.
In some cases it results in a failure to properly initialize video capture and output (i.e. in a white screen).
What I'm trying to achieve is to have the video output visible at all times, but to disable the actual processing of frames (bar codes recognition) during animations, alert views presentation, etc. in order to increase performance and save battery.
The only option to disable the processing while keeping the video output seems to be to set delegate to nil.
However, in certain cases it results in the aforementioned "white screen".

**Comment by cwalcott** [comment]
Hi, sorry for the long delay on responding. I'm not able to reproduce this, although perhaps recent changes to `ZXCapture` have inadvertently fixed it. Could you let me know if it's still occurring with the latest version?
