### ISSUE TITLE
Displaying possible result points with ZXCapture

### ISSUE THREAD

**Issue by Vadim-Yelagin** [TheLevelUp/ZXingObjC#170]
I would like to display possible result points during a QR code scan.
Without a ZXCapture this seems to be possible by setting resultPointCallback to ZXDecodeHints and collecting all the points passed to foundPossibleResultPoint: delegate method to some array. After a frame is processed, the points from the array can be displayed and the array cleared for the next frame.
However, I see no way to tell when a frame does get processes when using a ZXCapture. It only notifies its delegate of a finding an actual QR code (moreover, does this asynchronously, which can result in a race condition between foundPossibleResultPoint: and captureResult:result: calls).

**Comment by cwalcott** [comment]
I'm happy to look at a PR that adds this, but as you mention this is possible by not using `ZXCapture`.
