### ISSUE TITLE
BUG - Crash Using BarcodeScanner view in other project

### ISSUE THREAD

**Issue by FabienBourdonQualia** [TheLevelUp/ZXingObjC#172]
When i push BarcodeScannerViewController in Sample from an other view controller and i pop to the previous viewController after a while when a do this several time my app crash.

![crash](https://cloud.githubusercontent.com/assets/8776899/4269693/6d51f172-3cbf-11e4-91b4-f2f830dd4b3c.png)

**Comment by richsage** [comment]
I'm seeing the same thing - I use the example ViewController as a modal. Upon dismissing the controller after getting my result and repeating this open/close action a few times, I get the same error and my app crashes.

Stopping the capture and setting to the capture nil have no effect (not sure if they should!)

**Comment by richsage** [comment]
So, I was able to get a bit further with this. This code in the `stop` method:

    dispatch_async(dispatch_get_global_queue(DISPATCH_QUEUE_PRIORITY_DEFAULT, 0), ^{
      [self.session stopRunning];
    });

If I leave it at default priority, and then open/close/open/close the modal a few times, it seems that this code ends up out of sync, and the stop doesn't fire when you'd expect it to. Increasing the queue priority to HIGH makes it happen quicker (as you'd expect), and in a much more timely fashion - as soon as my modal is dismissed, the `stopRunning` call is made.

**Comment by ararog** [comment]
I'm also getting a crash with example code on modal viewcontroller.

**Comment by cwalcott** [comment]
Between ac28e51 and dadf516e48565dea261476c8d6071cad38cb0f0d I believe this should be fixed now.

**Comment by ararog** [comment]
Confirmed, version 3.0.4 is working as expected.

**Comment by wing0wind** [comment]
Excuse me,I found that as ararog say ,version 3.0.4 is working as expected,but version 3.1 crashed again in my app.
