### ISSUE TITLE
Can't scan ITF Barcode

### ISSUE THREAD

**Issue by rockbarato** [TheLevelUp/ZXingObjC#176]
Hi,

I'm trying to scan this image with the BarcodeScanner Example:

![img_7515](https://cloud.githubusercontent.com/assets/947557/4543564/64b8f442-4e2c-11e4-9973-1c15023e9568.JPG)

But the image is not scanned. Should be noted that the image is a ITF Barcode [(Interleaved 2 of 5)](http://en.wikipedia.org/wiki/Interleaved_2_of_5)

I'm using Xcode 6 with an iPhone 5 (iOS 8.0.2)

Any help would be appreciated.
Regards

**Comment by hdoria** [comment]
Same problem here.

**Comment by cwalcott** [comment]
I think this image is simply too large. When I scaled it down it was able to read it fine.
