### ISSUE TITLE
Some ASCII codes are not encoded correctly for PDF417

### ISSUE THREAD

**Issue by ted944** [TheLevelUp/ZXingObjC#181]
I have a string, with the first 3 characters as decimal "64", "10" and "30". 

A PDF417 barcode is generated but the first 3 characters are encoded as "0", "0" and "0".

Is this a known issue or something I did wrong?

Thanks

Ted

**Comment by cwalcott** [comment]
Could you share some sample code of the barcode generation?

**Comment by cwalcott** [comment]
Recently I've ported a bunch of PDF417 related improvements from ZXing, and also fixed a PDF417 related bug in ZXingObjC (9bf6e09915f3350b327cfc65575cdf2f8215c4d3). So hopefully that'll fix the problem you were having? Let me know.
