### ISSUE TITLE
Its take More CPU processs.

### ISSUE THREAD

**Issue by krtya-softwares** [TheLevelUp/ZXingObjC#192]
I have integrated library ZxingObjC. Due to this it increase CPU process upto 102.
Is there any way to reduce this. because it hit the Device.

![screen shot 2014-12-11 at 6 44 03 pm](https://cloud.githubusercontent.com/assets/8553052/5394892/cb6eb662-8168-11e4-90da-6dabb8884334.png)

**Comment by RyanCopley** [comment]
If you can post a sample app, I can diagnose why the performance issue is occurring.
