### ISSUE TITLE
ZXingObjC-osx test does not pass on japanese environment

### ISSUE THREAD

**Issue by hiralin** [TheLevelUp/ZXingObjC#194]
OSX test which  [ZXParsedReaderResultTestCase testVEvent] does not pass on japanese environment.
It seems calendar or locale dependent issue.

> ZXParsedReaderResultTestCase.m:266: error: -[ZXParsedReaderResultTestCase testVEvent] : ((goldenResult) equal to (displayResult)) failed: ("foo
> May 4, 2008 12:34:56 PM") is not equal to ("foo
> 5月 4, 2008 12:34:56 午後")

**Comment by cwalcott** [comment]
Thanks for the ticket. That's true, those tests assume the US locale. I don't think I'll have time to change those tests but I'm happy to look at a PR.
