### ISSUE TITLE
Some Time Fail to scan 1d type Barcode

### ISSUE THREAD

**Issue by maheshshahu** [TheLevelUp/ZXingObjC#199]
When we scan 1d type bar code it take more time to scan and some time it gives me wrong values.
Frequency of giving wrong values was 5/10.
How to resolve this?
Is this not support for 1d ?

**Comment by cwalcott** [comment]
Feel free to attach a particular barcode that's having trouble, but in general 1-D barcodes can be tough to scan because of their dimensions.
