### ISSUE TITLE
Long Integers in the data gets changed

### ISSUE THREAD

**Issue by ishansingh2003** [TheLevelUp/ZXingObjC#203]
I am having an issue in the PDF417 barcode. Suppose i pass a string which has a long number in it at some place barcode is generated but that value of string is getting changed. 

e.g string,

30|1|756645355|02112015|1319|111111111w1111111111111111111w|1111111111111w111111111111111w|g|

The long string of 1's is not readable in barcode. Or changed to some other value

**Comment by cwalcott** [comment]
Thanks for the report, should be fixed by 9bf6e09
