### ISSUE TITLE
Incorrect result on multiple scan of same Code-128

### ISSUE THREAD

**Issue by rkpant** [TheLevelUp/ZXingObjC#206]
I tried scanning same code -128 for multiple time, but found out that few of the results are incorrect.
![barcode](https://cloud.githubusercontent.com/assets/11421264/6593374/398317fc-c7fe-11e4-8329-67089dc6a3ed.png)

Correct Values ->
Code 128 - 03360016016606242001

Incorrect Values -> 
UPCE - 02252500
Code 128 - 42360016016606242028

This happens when I try to scan the same code multiple times. Though ~99% results I received were correct but few were incorrect also.  Please provide any help.

**Comment by mapo80** [comment]
Same problem here: https://github.com/TheLevelUp/ZXingObjC/issues/207

**Comment by cwalcott** [comment]
It's easy see UPC-E in other barcodes. I'd recommend restricting the scan to only look for Code-128 barcodes.

**Comment by rkpant** [comment]
@cwalcott .. yep that is one way of resolving this issue. But, my problem is that I have to support multiple barcodes, including code128 and upce. Could you give some more help to resolve this?

**Comment by cwalcott** [comment]
I'm afraid I'm not sure what else to do. It's very easy to get false positives with UPC-E. This comment from ZXing sums it up nicely: https://github.com/zxing/zxing/issues/247#issuecomment-61096540
