### ISSUE TITLE
Error decoding Code-128

### ISSUE THREAD

**Issue by mapo80** [TheLevelUp/ZXingObjC#207]
Hi,

there is a problem on decoding barcode code-128.
![fullsizerender](https://cloud.githubusercontent.com/assets/1677958/6636476/bc19b11c-c970-11e4-9ce9-b2d84b4bf746.jpg)

It's not recognized every time and when recognized is of type UPCE.

I've tried with other app on AppStore and it's recognized correctly.

Is this a bug?

**Comment by cwalcott** [comment]
It's easy see UPC-E in other barcodes. I'd recommend restricting the scan to only look for Code-128 barcodes.
