### ISSUE TITLE
missing pdf417

### ISSUE THREAD

**Issue by tospery** [TheLevelUp/ZXingObjC#209]
when i run BarcodeScanner to scan pdf417, it can't recognize, only success one time in try 20 times.

**Comment by cwalcott** [comment]
Hi, what version of ZXingObjC are you using?

**Comment by tospery** [comment]
when i push to scan, it don't work:
LLHomeScanViewController *scanVC = [[LLHomeScanViewController alloc] init];
scanVC.hidesBottomBarWhenPushed = YES;
[self.navigationController pushViewController:scanVC animated:YES];


// LLHomeScanViewController.m ->

@interface LLHomeScanViewController ()
@property (nonatomic, strong) ZXCapture *capture;
@end

@implementation LLHomeScanViewController

- (void)viewDidLoad {
    [super viewDidLoad];
    // Do any additional setup after loading the view from its nib.
    self.capture = [[ZXCapture alloc] init];
    self.capture.camera = self.capture.back;
    self.capture.focusMode = AVCaptureFocusModeContinuousAutoFocus;
    self.capture.rotation = 90.0f;
    
    self.capture.layer.frame = self.view.bounds;
    [self.view.layer addSublayer:self.capture.layer];
}

- (void)viewWillAppear:(BOOL)animated {
    [super viewWillAppear:animated];
    
    self.capture.delegate = self;
    self.capture.layer.frame = self.view.bounds;
}

- (BOOL)shouldAutorotateToInterfaceOrientation:(UIInterfaceOrientation)toInterfaceOrientation {
    return toInterfaceOrientation == UIInterfaceOrientationPortrait;
}

- (void)captureResult:(ZXCapture *)capture result:(ZXResult *)result {
    NSLog(@"【YJX_TEMP】%s", __func__);
    if (!result) return;
    DDLogDebug(@"nContent: %@", result.text);
    // Vibrate
    AudioServicesPlaySystemSound(kSystemSoundID_Vibrate);
    [self.capture stop];
}


Now, i push this

**Comment by cwalcott** [comment]
What is the specific problem you're having?

**Comment by tospery** [comment]
when scan, the "- (void)captureResult:(ZXCapture *)capture result:(ZXResult *)result" is not be called. You can get the test demo from http://pan.baidu.com/s/1qWp2qgk

**Comment by tospery** [comment]
I have solved this problem by using Pod, thx.
