### ISSUE TITLE
the scan result of pdf417 is often wrong

### ISSUE THREAD

**Issue by tospery** [TheLevelUp/ZXingObjC#210]
When scanning the pdf417, it is too slowly, and results of scan often are different when scanned multiple times. (Most of results are wrong, because they are not the same as the result of using http://pdf417.mobi/ library)
    can you optimize the pdf417?

**Comment by cwalcott** [comment]
I just noticed this myself. I believe 4ed07b8be87fb87ed11862a17b695b61c857ed08 should fix it.
