### ISSUE TITLE
usually crash at [ZXCapture dealloc]

### ISSUE THREAD

**Issue by tospery** [TheLevelUp/ZXingObjC#212]
- (void)dealloc {
  if (_lastScannedImage) {
    CGImageRelease(_lastScannedImage); // crash here
  }

  if (_session && _session.inputs) {
    for (AVCaptureInput *input in _session.inputs) {
      [_session removeInput:input];
    }
  }

  if (_session && _session.outputs) {
    for (AVCaptureOutput *output in _session.outputs) {
      [_session removeOutput:output];
    }
  }
} // or crash here

**Comment by tospery** [comment]
malloc: *** error for object 0x1666cc90: pointer being freed was not allocated
*** set a breakpoint in malloc_error_break to debug

**Comment by MusaabQamar** [comment]
I am facing the same problem and could not found any help yet. Any Body here please help. We need your urgent attention. I am stuck at this point. Please help.

**Comment by nverinaud** [comment]
Same here but commenting `dealloc` does not solve the problem. I guess it's the memory management of the last scanned image which is not correct. I'm investigating...

**Comment by nverinaud** [comment]
OKAY ! I found a fix !

You should remove the `ZXCapture.layer` from your layer hierarchy in your `dealloc`.

This is how my `dealloc` now looks like :

```
- (void)dealloc
{
    [self.capture.layer removeFromSuperlayer];
    self.capture.delegate = nil;
    [self.capture stop];
}
```

**Comment by vvit** [comment]
@nverinaud Thanks for the fix! Recently my app started crashing but your fix has helped.
