### ISSUE TITLE
ARC Semantic Issue: Multiple methods named 'initWithType:' found with mismatched result, parameter type or attributes

### ISSUE THREAD

**Issue by jpage4500** [TheLevelUp/ZXingObjC#216]
Hi,

Just recently our build server started to fail with the error below. We're using 3.0.4 cocoapod and that hasn't changed in a while.

I don't see this issue while compiling locally but I'm wondering if our build server was upgraded to the latest version of XCode which is causing this? In any case, I wanted to report it in case others start seeing this error too:

Error in beepngo-ios/Pods/ZXingObjC/ZXingObjC/client/result/ZXParsedResult.m
ARC Semantic Issue: Multiple methods named 'initWithType:' found with mismatched result, parameter type or attributes

pod 'ZXingObjC', '3.0.4'              # barcode to image generation (https://github.com/TheLevelUp/ZXingObjC)

**Comment by joaomvfsantos** [comment]
Also started getting this error once I updated to XCode 6.3

**Comment by jpage4500** [comment]
A temporary fix is to change the podfile to this.. i guess the 'repo' version isn't updated with the latest from here.

pod 'ZXingObjC', :git => 'https://github.com/TheLevelUp/ZXingObjC'

**Comment by joaomvfsantos** [comment]
Great, this solves it for now. Thank you.

**Comment by Dev-** [comment]
I had at the exact error after upgrading to Xcode 6.3 as well the suggested fix works for me too. Thanks to - @jpage4500 and @joaomvfsantos .

**Comment by mghersi65** [comment]
return [[self alloc] initWithTypes:type error: NULL];

**Comment by vixentael** [comment]
thanks @jpage4500, solution works for me too.
it would be nice to have release with this fix and to link pod to it
