### ISSUE TITLE
With v3.1.0, Often parsed error for PDF417. 

### ISSUE THREAD

**Issue by tospery** [TheLevelUp/ZXingObjC#218]
In fact the value is G0353141140061934133LBNLPNPNMHLBBOHGGD000, but often parse it to 47075146、02274849 or 47075146, and so on.

**Comment by aibeke** [comment]
I do not get scanned pdf417. Other formats work.
Can you tell how you're doing?

**Comment by aibeke** [comment]
I found very simple [solution](http://www.infragistics.com/community/blogs/torrey-betts/archive/2013/10/10/scanning-barcodes-with-ios-7-objective-c.aspx).
