### ISSUE TITLE
Unable to read this qrcode (but original zxing can)

### ISSUE THREAD

**Issue by skylook** [TheLevelUp/ZXingObjC#219]
The following image is a badcase of qrcode. It can scan & read successfully by original zxing java version (both on web decoder : http://zxing.org/w/decode.jspx and its scanner demo), but cannot be read by ZXingObjC at all.

Can any body fix this problem? Thx.

![wangge_1](https://cloud.githubusercontent.com/assets/3205308/7290135/ddf71822-e9ac-11e4-9f95-a5722de7f0f8.png)

**Comment by iGoreSchmidt** [comment]
i can add one more QR with same issue- I can't read it with ZXingObjC but zxing on android and website read it.
![what-wrong-with-it](https://cloud.githubusercontent.com/assets/3225843/10214378/d81ca2e8-6817-11e5-8498-ff5050bc3f96.png)
Any solution?
