### ISSUE TITLE
On iPhone 6 Plus (8.3), scan to pdf417, failed rate is 90%.

### ISSUE THREAD

**Issue by tospery** [TheLevelUp/ZXingObjC#220]
On iPhone 5C (7.0), failed rate is 10%

**Comment by aibeke** [comment]
I used 3.1.0 version and I want scan **pdf417** format barcode, but I have not never happened.
[Barcodes](https://www.google.com/search?q=pdf417&client=firefox-b-ab&source=lnms&tbm=isch&sa=X&ved=0ahUKEwjQkamv2qzPAhXBYpoKHXw8AcsQ_AUICCgB&biw=1767&bih=952) from google.

Other formats work. Help.

iPhone 5, ios version: 10.0.2
