### ISSUE TITLE
Swap cropping & rotation for perf improvement

### ISSUE THREAD

**Issue by dpolivy** [TheLevelUp/ZXingObjC#222]
I'm not sure if this is a feasible change (as it is breaking), but it might have some perf benefits when cropping the scanned area to a small portion of the video capture.

I've modified my use of ZXCapture.m to first apply the crop rect to the image, and then do the rotation. It's basically a reordering of the code here:

https://github.com/TheLevelUp/ZXingObjC/blob/master/ZXingObjC/client/ZXCapture.m#L349-L357

This does mean that the crop rect does have to be specified in coordinates relative to the video's native orientation -- however that's not a huge deal as long as that is known by the developer. It is potentially a breaking change, though.

I can work up a PR if you'd like, but I figured I'd first test the waters and see if this improvement were valuable to others.

**Comment by benjohnde** [comment]
How's the state here @dpolivy ?

**Comment by dpolivy** [comment]
@benjohnde I haven't run any of the tests -- but I've been using it in my app for a while without any issues. Here's the code I modified:

````
    CGImageRef videoFrameImage = [ZXCGImageLuminanceSource createImageFromBuffer:videoFrame];

    // If scanRect is set, crop the current image to include only the desired rect
    if (!CGRectIsEmpty(self.scanRect)) {
      CGImageRef croppedImage = CGImageCreateWithImageInRect(videoFrameImage, self.scanRect);
      CGImageRelease(videoFrameImage);
      videoFrameImage = croppedImage;
    }

    CGImageRef rotatedImage = [self createRotatedImage:videoFrameImage degrees:self.rotation];
    CGImageRelease(videoFrameImage);
    self.lastScannedImage = rotatedImage;
````

**Comment by benjohnde** [comment]
I will look into that, thanks!

**Comment by benjohnde** [comment]
As said, we are using quite the same approach. Do you want to prepare a pull request? I mean, I can implement it myself for fun, but it is kind of your contribution.
