### ISSUE TITLE
Wrong Barcode recognised

### ISSUE THREAD

**Issue by docterd** [TheLevelUp/ZXingObjC#223]
Hi,

for some reason, ZXingObjC reads this barcode wrong. It seems to be a special case, especially because the iOS7 Inbuilt API doesn't recognise it at all. Amazon's Barcode Scanner on the other hand works fine.

![img_0346](https://cloud.githubusercontent.com/assets/199578/7460755/b7ad747a-f2a5-11e4-99b3-c16190aab0c8.jpg)

**Comment by smikle** [comment]
Hi,

I have the same problem with this barcode.
And I can add one more, I think this is the wrong barcode. 
http://www.google.ru/imgres?imgurl=http://www.diglabel.ru/upload/iblock/415/01610_0019_2.jpg&imgrefurl=http://www.diglabel.ru/spetsializatsiya/etiketki-so-shtrikhkodom-i-qr-kodom.php&h=180&w=416&tbnid=lyYV9HhMT9O0TM:&zoom=1&docid=Rhzez0J2HwPEpM&ei=afaLVZSwEYauswH8-pXYCQ&tbm=isch&ved=0CFEQMygXMBc
But it would be better that he did not recognize it.

**Comment by Paschmid** [comment]
Hey
I've scanned it with ZXing and it gave me 5168847001729 (which is actually what's encoded). The barcode for the given number can't be generated since the checksum is wrong. Therefore, the number doesn't correspond to the barcode.
