### ISSUE TITLE
Pod install takes a long time

### ISSUE THREAD

**Issue by ltebean** [TheLevelUp/ZXingObjC#224]
Could you move the lib code to a separate project, since the current project is very big, the first time running pod install takes lots of time, thanks~

**Comment by krutarth** [comment]
+1, Tests are about 132MB. It would be great to seperate the lib into a seperate project.

**Comment by bryanhathaway** [comment]
Yes please. It's a pain to use as a submodule because of the massive size of the test case resource files

**Comment by gitabdelkarim** [comment]
Yes please, even with the last version (3.1.0), the "Pod install" takes a loooong time, IT'S NOT NORMAL !!!

**Comment by bawn** [comment]
same problem

**Comment by benjohnde** [comment]
yeap, but I think the whole git repo is getting fetched anyway, so just moving the test files in a new subrepo would not solve the problem. Maybe we would need to split the project in two new repos. can anyone concur?

**Comment by cwalcott** [comment]
The problem is that even if we get rid of all the test images, they still live in the git history, so I don't think it would help the time it takes to clone the repo.

**Comment by benjohnde** [comment]
Yeap this is what I meant. The whole repo is getting fetched. The only way would be to split this repo.

**Comment by bawn** [comment]
@ltebean @krutarth @bryanhathaway @gitabdelkarim @benjohnde @cwalcott I have a temporary solution, first download the entire project, then ZXingObjC.podspec ZXingObjC folders and files into your project directory,Last edited Podfile, to set up local files referenced ZXingObjC
```
pod 'ZXingObjC', :path => '~/youfilepath/ZXingObjC'
```
You can also refer to the official documentation [cocopods](https://guides.cocoapods.org/using/the-podfile.html#using-the-files-from-a-folder-local-to-the-machine) `Using the files from a folder local to the machine.`

This way when you update pod again when you do not need to wait any longer，But the ZXingObjC on local certainly is not good, so we just added the file and then delete, modify podfile is again
```
pod 'ZXingObjC'
```
Then update pod again,You will find that it has no need to update ZXingObjC

**Comment by cwalcott** [comment]
Also after the first `pod install`, subsequent ones should be much faster assuming the `Pods` directory still exists.

**Comment by nabilfreeman** [comment]
After I install the Pod, can I safely delete the large files such as the tests without affecting the functionality of the library? I'm thinking about disk space...

**Comment by benjohnde** [comment]
Sure you can. The large files (I guess you mean the resource files for the tests) can be deleted w/o disturbing the normal functionality of the library. They are only required to run all the black box tests.
