### ISSUE TITLE
ZXCapture doesn't assign reader on mac.

### ISSUE THREAD

**Issue by IvanDev** [TheLevelUp/ZXingObjC#225]
**Steps to reproduce:**
On latest version 3.1.0 build and run BarcodeScannerOSX example.
It doesn't recognise anything.
**Reason:**
Turns out NSClassFromString(@"ZXMultiFormatReader") returned nil in ZXCapture init method.
**Quick dirty fix:**
Assigning reader to capture object fixes issue:
```
self.capture = [[ZXCapture alloc] init];
self.capture.reader=[ZXMultiFormatReader reader];
```

**Comment by benjohnde** [comment]
Should be fixed. Current HEAD works.
