### ISSUE TITLE
High cpu usage after calling stop.

### ISSUE THREAD

**Issue by paweljasinski** [TheLevelUp/ZXingObjC#227]
I run the example for ios code in my app. After the barcode is reported by `captureResult`, I call capture.stop and perform segue to the next view. I do not rearm with `[capture start]`.
Device is warm and debugger reports 100% cpu utilization.
There are two offending threads, one of them is definitely still trying to recognize barcode (`ZXPDF417Detector`).
When I change to `[capture.hard_stop]`, the cpu utilization drops to 0.

**Comment by benjohnde** [comment]
You may have an example app for that? It works fine for me.

**Comment by paweljasinski** [comment]
I can not dump the code I have as-is. When I have a moment I will try to come up with a self containing test case.

**Comment by Paschmid** [comment]
I have the same problem like @paweljasinski when presenting a new UIViewController from the barcode scanner. I found out that the problem occurs when viewWillDisappear is implemented in the UIViewController where the ZXCapture resides. Inside the viewWillDisappear, `[capture stop]` is called. After the stop, `- (void)runActionForKey:(NSString *)key object:(id)anObject arguments:(NSDictionary *)dict` is called in the ZXCapture with kCAOnOrderOut which triggers a start.
