### ISSUE TITLE
ZXMultiDetector.h is imported on ZXingObjCCore.h

### ISSUE THREAD

**Issue by banaslee** [TheLevelUp/ZXingObjC#229]
This is an issue if I don't need to support QR codes and I'm using just the OneD subspec.

**Comment by benjohnde** [comment]
Why is this an issue?

**Comment by mgrebenets** [comment]
The podspec includes supspecs, but those pretty much can't be used because of inter-module dependencies like tis. I believe #253 and #254.

**Comment by benjohnde** [comment]
Yeap you're right sir.
