### ISSUE TITLE
Won't encode Code93 or UPC-E formats

### ISSUE THREAD

**Issue by xander94** [TheLevelUp/ZXingObjC#232]
Been using the ZXing barcode encoder in an iOS app I'm developing. It works fine for generating any barcode format except for Code93 (kBarcodeFormatCode93) and UPC-E (kBarcodeFormatUPCE). The result it returns is null for these two formats.

Anyone else having these problems?

**Comment by rbresjer** [comment]
I also tried encoding Code 93 barcodes. According to the README the library supports it:
> The following barcodes are currently supported for both encoding and decoding:
> [..] Code 93 [..]
However when looking at `ZXMultiFormatWriter.m` it's clear the library doesn't support it. I think the README should be updated?

**Comment by benjohnde** [comment]
You have a point there :) just updated the README.
