### ISSUE TITLE
Confusing undocumented magic numbers in ZXCGImageLuminanceSource.m 

### ISSUE THREAD

**Issue by cortices** [TheLevelUp/ZXingObjC#244]
What is the function of these numbers in the section of ZXCGImageLuminanceSource.m which are part of the de-premultiplication process? I cannot find them referenced anywhere else, or any documentation about them.

https://github.com/TheLevelUp/ZXingObjC/blob/master/ZXingObjC/client/ZXCGImageLuminanceSource.m#L232

**Comment by benjohnde** [comment]
Good point, should be documented.

**Comment by benjohnde** [comment]
Hint is given in the source: "https://github.com/TheLevelUp/ZXingObjC/blob/master/ZXingObjC/client/ZXCGImageLuminanceSource.m#L222".
