### ISSUE TITLE
*** -[AVCaptureVideoDevice setTorchMode:] - the passed torchMode 0 is not supported by the device.  Use -isTorchModeSupported: to discover valid torch modes.

### ISSUE THREAD

**Issue by zhanjiarong** [TheLevelUp/ZXingObjC#247]
Some devices don't support TorchModeOn. So my app crached on some devices with reason "-[AVCaptureVideoDevice setTorchMode:] - the passed torchMode 0 is not supported by the device". 
 On line 177 of file ZXingCapture.m as follows must judge if the device support TorchModeOn.

The source code:
- (void)setTorch:(BOOL)torch {
  _torch = torch;
  
  [self.input.device lockForConfiguration:nil];
  self.input.device.torchMode = self.torch ? AVCaptureTorchModeOn : AVCaptureTorchModeOff;
  [self.input.device unlockForConfiguration];
  }

My code:
- (void)setTorch:(BOOL)torch {
  _torch = torch;
  
  if ([self.input.device isTorchModeSupported:AVCaptureTorchModeOn] && [self.input.device isTorchModeSupported:AVCaptureTorchModeOff]) {
      [self.input.device lockForConfiguration:nil];
      self.input.device.torchMode = self.torch ? AVCaptureTorchModeOn : AVCaptureTorchModeOff;
      [self.input.device unlockForConfiguration];
  }
  }

**Comment by benjohnde** [comment]
Maybe torch is broken or you are using a device without torch. Nonetheless, the example application is not really good, as well as the current capture module. Should be rewritten.
