### ISSUE TITLE
Manual installation

### ISSUE THREAD

**Issue by tonyrh** [TheLevelUp/ZXingObjC#249]
Can you detail the steps needed to manually (no cocoapods) install the library please?
Thanks!

**Comment by benjohnde** [comment]
Does this help: https://github.com/TheLevelUp/ZXingObjC/issues/233? Otherwise I may find time to write a small guide tomorrow :) Cheers!

**Comment by tehilata** [comment]
I looked at #233 but it didn't help me.
Could you write small guide? It will be very helpful !
Thanks :)
