### ISSUE TITLE
No results for any ZXCapture _sessionPreset higher than Medium

### ISSUE THREAD

**Issue by longhoanguyen** [TheLevelUp/ZXingObjC#251]
I can't seem to get any results when I change the _sessionPreset to AVCaptureSessionPresetHigh or AVCaptureSessionPresetPhoto (or anything higher resolution than Medium).

I tested this (with large one-dimensional barcodes) on both an iPad 2 and iPad Air 2, and not a single result came back from the example iOS app.

I also tried to reduce the size of the scanner view rect, but that doesn't work either.

**Comment by benjohnde** [comment]
What happened here? :) Everything good now?

**Comment by longhoanguyen** [comment]
The scanning isn't as responsive as when set to Medium. It takes a bit longer, and I have to change the frame size ratio for the CAffeine transform in ViewController.m

**Comment by longhoanguyen** [comment]
I'm still not able to get any decent (or any results at all usually) results with the preset at High. Any small sized barcode is impossible to read :(
