### ISSUE TITLE
Carthage support

### ISSUE THREAD

**Issue by FixedLab** [TheLevelUp/ZXingObjC#257]
Carthage support will be very appreciate. Cocoa pods is old, and Carthage is the new "best way" to import external framework.

**Comment by LukeDefeo** [comment]
+1

**Comment by CodeKunal** [comment]
Is there some way we can use carthage to include this framework in our project?

**Comment by mgrebenets** [comment]
CocoaPods is still alive an kicking and they have a thing called [Rome](https://github.com/neonichu/Rome) which is somewhat close to Carthage :)

Anyways, one of the major differences of Carthage from CocoaPods is that there's no need for podspecs or similar metadata. As long as Xcode project builds on it's own it will build with Carthage almost in all cases.

Have you tried to do `github "TheLevelUp/ZXingObjC"` in Cartfile?
I didn't try it personally, I had to integrate it with CocoaPods, but that's the gist of Carthage, it should _just_ work.
