### ISSUE TITLE
Update Cocoapods version

### ISSUE THREAD

**Issue by andr3a88** [TheLevelUp/ZXingObjC#269]
Hi, 
is possible to update the version on Cocoapods? The actual pod version (3.1.0) is older than 10 months.

Thank you.

**Comment by 4brunu** [comment]
Yes please.
I just lost hour with a bug in the scan area that is fixed in the repository version, but not the cocoapods version.
@benjohnde Could you please update the cocoapods version please?
Thanks

**Comment by benjohnde** [comment]
🚀 ZXingObjC (3.2.1) successfully published. Enjoy :)
