### ISSUE TITLE
malloc/free crash when generating PDF417 image

### ISSUE THREAD

**Issue by alex-bambora** [TheLevelUp/ZXingObjC#270]
### The following will crash an application 95% of the time because of a malloc/free.

```
    NSError *error = nil;
    CGFloat multiplier = .1;
    CGFloat width = 423.0, height = 101.0;

    // string must have format: 'dddd:xxxxyyyy', where x,y are letters and d is a digit (0-9). Also, 'dddd' can be 2 to 7 in length (dd, ddd, dddd, ...)
    NSString *string = @"1234:xxxxyyyy";

    ZXEncodeHints *hints = ZXEncodeHints.hints;
    hints.margin = @0.;
    ZXBitMatrix *matrix = [ZXPDF417Writer.new encode:string format:kBarcodeFormatPDF417
                                               width:width*multiplier height:height*multiplier hints:hints error:&error];

    if (!error && matrix) {
        CGImageRef cgImg = [ZXImage imageWithMatrix:matrix].cgimage;
        return [UIImage imageWithCGImage:cgImg
                                   scale:UIScreen.mainScreen.scale
                             orientation:UIImageOrientationUp];
    }
```

Usually the crash occurs some time after this code runs, somewhere in system calls such as a UI layout.

**Comment by mrianmerry** [comment]
I had a very similar issue to this myself just recently, and found that there is a Zombie in the `[[ZXImage initWithMatrix:matrix] cgImage]` call.

My workaround, which seems to satisfy Instruments and the retain count, and resolves the issue with crashes, is to replace the assignment like so:
```Objective-C
ZXImage *zxImage = [ZXImage imageWithMatrix:matrix];
CGImageRef cgImage = [zxImage cgImage];
UIImage *uiImage = [UIImage imageWithCGImage:cgImage];
```

**Comment by benjohnde** [comment]
Hmmm not sure if this is a real bug. `ZXImage` gets deallocated right after it was initialised. Thus, `[self dealloc]` gets invoked and releases the image.

Maybe we should add another method to directly retrieve an `UIImage` from `ZXImage`?
