### ISSUE TITLE
Change to ZXCapture.m

### ISSUE THREAD

**Issue by mapo80** [TheLevelUp/ZXingObjC#274]
There's an an error on ZXCapture.m for iPad 2.

This should be used:
`- (AVCaptureSession *)session {
  if (!_session) {
    _session = [[AVCaptureSession alloc] init];

```
AVCaptureDevice *zxd = [self device];
//Fix for iPad 2
if (zxd) {

    if([zxd supportsAVCaptureSessionPreset:AVCaptureSessionPreset1920x1080]){
        _sessionPreset = AVCaptureSessionPreset1920x1080;
    }else{
        _sessionPreset = AVCaptureSessionPreset1280x720;
    }
}else{
    _sessionPreset = AVCaptureSessionPreset1280x720;
}

[self replaceInput];
```

  }

  return _session;
}`
Now there's:

`if([_session canSetSessionPreset:AVCaptureSessionPreset1920x1080]){
      _sessionPreset = AVCaptureSessionPreset1920x1080;
    } else {
      _sessionPreset = AVCaptureSessionPreset1280x720;
    }
`

**Comment by quangmv** [comment]
Thanks, It worked for me.

**Comment by mapo80** [comment]
This fix must be done because on iPad 2 apps that use ZXingObjC crash.
Now I have to fix manually ZXingObjC but I can't library as is on github.

Thanks.
