### ISSUE TITLE
ZXingObjC issue while importing to a new Project using Xcode 7.3

### ISSUE THREAD

**Issue by abinkoshycheriyan** [TheLevelUp/ZXingObjC#276]
I am using ZXingObjC library for creating and reading QRCode in may application and was working fine.

Recently I updated Xcode to 7.3(7D175) and created a new project and imported the same files for generating QRCode. But now I am not able to compile the project and is getting quite a lot number of errors.

Some errors are described below:

```
1.ZXingObjC/core/ZXResultPoint.h:21:37: No type or protocol named 'NSCopying'
2.ZXingObjC/core/ZXResultPoint.h:21:28: Cannot find interface declaration for 'NSObject', superclass of 'ZXResultPoint'
3. Expected a type -> + (void)orderBestPatterns:(NSMutableArray *)patterns;
4.  ZXingObjC/common/ZXBitArray.h:28:41: Unknown type name 'int32_t' for @property (nonatomic, assign, readonly) int32_t *bits;
5. ZXingObjC/common/ZXBitMatrix.h:31:26: Cannot find interface declaration for 'NSObject', superclass of 'ZXBitMatrix' @interface ZXBitMatrix : NSObject <NSCopying>
```

Can anybody help me in resolving these errors? Any idea ???

**Comment by abinkoshycheriyan** [comment]
![screen shot 2016-03-29 at 4 21 46 pm](https://cloud.githubusercontent.com/assets/1751197/14105597/3f7318b0-f5ca-11e5-8ad0-e3422ae52bd4.png)

**Comment by zy30651** [comment]
I don't know what's wrong made the bug. But you can fix it。
Create a Prefix-Header.pch file。And #import <UIKit/UIKit.h>
#import <Foundation/Foundation.h>  。

**Comment by tranhieutt** [comment]
First, you create ios-Prefix.pch file:

`#ifdef __OBJC__
  #import <Foundation/Foundation.h>
#endif`

Then, in Build Setting/ Appe LLVM 7.1 - Language,
you should set Precomplie Prefix Header is YES
and:
Prefix Header: [path]/ios-Prefix.pch
