### ISSUE TITLE
Cocoapods, project malfunction

### ISSUE THREAD

**Issue by bichorocket** [TheLevelUp/ZXingObjC#277]
Use cocoa pods for install ZXingObjc miscalculates positioning the scanning area, two days wasted :(

**Comment by 4brunu** [comment]
I have the same problem, did you solve it?

**Comment by benjohnde** [comment]
It should be accurate for two-dimensional codes. I guess you need it for one-dimensionals.

**Comment by tranhieutt** [comment]
Today, i have the same problem with cocoapod.
`      if (self.delegate) {
        ZXBinaryBitmap *bitmap = [[ZXBinaryBitmap alloc] initWithBinarizer:binarizer];

        NSError *error;
        ZXResult *result = [self.reader decode:bitmap hints:self.hints error:&error];
        if (result) {
          dispatch_async(dispatch_get_main_queue(), ^{
            [self.delegate captureResult:self result:result];
          });
        }
      }`

result is nil???

**Comment by tranhieutt** [comment]
today, i just config Podfile with:

`platform :ios, '7.0'`

`pod 'ZXingObjC', :git => 'https://github.com/TheLevelUp/ZXingObjC.git', :commit => '868a42d'`

So, everything ok, I can scan bar-code normal with config above

I don't use:
`platform :ios, '7.0'`
`pod 'ZXingObjC', '~> 3.0'`

It's not work!

**Comment by benjohnde** [comment]
🚀 ZXingObjC (3.2.1) successfully published.

Please try again with current podspec.
