### ISSUE TITLE
ZXing is very hot

### ISSUE THREAD

**Issue by chymse67** [TheLevelUp/ZXingObjC#293]
iDevice very hot when using ZXing within about 2 minutes

**Comment by gersonmendes** [comment]
@chymse67 What was your problem? And how did you solve? Thanks.

**Comment by RajkumarLoganathan** [comment]
Device temperature is increasing frequently. Can you please help me on this.
![screen shot 2016-11-24 at 10 41 13 am](https://cloud.githubusercontent.com/assets/5761967/20587293/56eea1d8-b232-11e6-940e-fe585788ef9e.png)
![screen shot 2016-11-24 at 10 41 38 am](https://cloud.githubusercontent.com/assets/5761967/20587294/576ce8cc-b232-11e6-938d-f65eb52bc77f.png)

**Comment by coulCod** [comment]
Why this issue closed without the any answer?
