### ISSUE TITLE
Building the library on Xcode 8

### ISSUE THREAD

**Issue by undsoft** [TheLevelUp/ZXingObjC#296]
Hi,

I have downloaded the library with the intention of slightly modifying it.
But I cannot get the vanilla code to build on my xcode 8 beta 5. It still builds just fine on xcode 7.
The errors I get are somewhat weird:

> ZXingObjC-master/ZXingObjC/client/ZXCapture.m:99:20: Assigning to 'id<CALayerDelegate> _Nullable' from incompatible type 'ZXCapture *const __strong'

> ZXingObjC-master/ZXingObjC/client/ZXCapture.m:516:36: Use of undeclared identifier 'AVCaptureSessionPreset1920x1080'

For the second error, I tried doing 
`#import <AVFoundation/AVCaptureSession.h>`
and changing deployment target.

Any ideas?

**Comment by monoqlo** [comment]
You should declare `CALayerDelegate` like this.

```objc
@interface ZXCapture () <CALayerDelegate>
```

**Comment by benjohnde** [comment]
Should be fixed
