### ISSUE TITLE
[!] Error installing ZXingObjC with pod

### ISSUE THREAD

**Issue by semnyqu** [TheLevelUp/ZXingObjC#301]
Installing ZXingObjC (3.1.0)

[!] Error installing ZXingObjC
[!] /usr/bin/git clone https://github.com/TheLevelUp/ZXingObjC.git /var/folders/x2/270gwz7938g38n5x45c7rdjw0000gn/T/d20160831-69461-13vwg4c --template= --single-branch --depth 1 --branch 3.1.0

Cloning into '/var/folders/x2/270gwz7938g38n5x45c7rdjw0000gn/T/d20160831-69461-13vwg4c'...
error: RPC failed; curl 56 SSLRead() return error -9845
fatal: The remote end hung up unexpectedly
fatal: early EOF
fatal: index-pack failed

**Comment by benjohnde** [comment]
Check, the problem was Github related. Should work for now.
