### ISSUE TITLE
podspec for 3.2.0 is not pushed

### ISSUE THREAD

**Issue by monoqlo** [TheLevelUp/ZXingObjC#308]
The latest podspec on cocoapods indicates 3.1.0, so we can't install this library by cocoapods if we use Xcode 8.

Could you push the podspec for 3.2.0?

**Comment by wrtsprt** [comment]
+1

**Comment by s9574** [comment]
+1

**Comment by oskargargas** [comment]
Yup, +1 also. Subscribing for the issue.

**Comment by michael-li-flipp** [comment]
Instead of manually downloading the release, you can also point Cocoapods to the repo, saves you the step of manually downloading.
`pod 'ZXingObjC', :git => 'https://github.com/TheLevelUp/ZXingObjC'`

**Comment by cdeorio** [comment]
+1 using manual process

**Comment by dklinzh** [comment]
try this way: 
pod 'ZXingObjC', :git => 'https://github.com/TheLevelUp/ZXingObjC.git', :commit => 'fa2f046'

**Comment by gersonmendes** [comment]
+1

**Comment by xiliyue** [comment]
+1

**Comment by huhood** [comment]
+1

**Comment by Cee** [comment]
+1

**Comment by benjohnde** [comment]
🚀 ZXingObjC (3.2.1) successfully published. Enjoy :)
