### ISSUE TITLE
set  sessionPresst of ZXCapture with AVCaptureSessionPresetHigh, it is not work!

### ISSUE THREAD

**Issue by HuangXiaoxing** [TheLevelUp/ZXingObjC#312]
It will be not work When i set sessionPresst of ZXCapture with AVCaptureSessionPresetHigh,and with last step i did not set scanRect it can work.Only i set scanRect with a CGRect value,it will be not work when sessionPresst is equal AVCaptureSessionPresetHigh.

**Comment by LoseAnson** [comment]
I find that when you set sessionPresst,It does not set the property AVCaptureSession object in ZXCapture.

**Comment by benjohnde** [comment]
Yeap, that is indeed a bug! Thanks for reporting.

**Comment by benjohnde** [comment]
I conduct a fix https://github.com/TheLevelUp/ZXingObjC/pull/428.
