### ISSUE TITLE
[!] Error installing ZXingObjC

### ISSUE THREAD

**Issue by TangledHusky** [TheLevelUp/ZXingObjC#313]
Installing ZXingObjC (3.1.0)

[!] Error installing ZXingObjC
[!] /usr/bin/git clone https://github.com/TheLevelUp/ZXingObjC.git /var/folders/mw/yk_5gldd6t95rnjh5lryqc_m0000gn/T/d20160929-12874-44n40p --single-branch --depth 1 --branch 3.1.0

Cloning into '/var/folders/mw/yk_5gldd6t95rnjh5lryqc_m0000gn/T/d20160929-12874-44n40p'...
error: RPC failed; curl 18 transfer closed with outstanding read data remaining
fatal: The remote end hung up unexpectedly
fatal: early EOF
fatal: index-pack failed

who can help me?

**Comment by zawaliang** [comment]
me too,help

**Comment by dklinzh** [comment]
pod 'ZXingObjC', :git => 'https://github.com/TheLevelUp/ZXingObjC.git', :commit => 'fa2f046'

I used manual configuration like the code above to solve this problem temporarily.

**Comment by Jeff-F** [comment]
+1

**Comment by TangledHusky** [comment]
i solved it with  pod 'ZXingObjC', '~> 3.0'

try it

**Comment by benjohnde** [comment]
🚀 ZXingObjC (3.2.1) successfully published. Enjoy :)
