### ISSUE TITLE
cpu high 100% and hot

### ISSUE THREAD

**Issue by totemtec** [TheLevelUp/ZXingObjC#314]
Xcode 8.0, iPhone 6p, iOS 8.3
![screen shot](http://totemtec.sinaapp.com/images/screen%20shot.png)

**Comment by namnguyens** [comment]
I can confirm this issue - the is a big problem as the phone (in my case iPhone 7) gets really hot.

**Comment by RajkumarLoganathan** [comment]
I am also facing the same problem for all devices (iPhone 5s, 6, 6s) and Xcode 7 & 8. Can you please help on this.

**Comment by 948769029** [comment]
I am also facing the same problem for all devices (iPhone 5s, 6, 6s) and Xcode 7 & 8. Can you please help on this.

**Comment by gerardojchv** [comment]
I have the same problem. IPhone 6s and Xcode 7.3.1. 
CPU: 100% and device is very hot. 
Can you please help on this

**Comment by xiliyue** [comment]
I have the same problem. IPhone 6s and Xcode 7.3.1.
CPU: 100% and device is very hot.
Can you please help on this

**Comment by PlasmaSoftUK** [comment]
I have similar issues, testing with an iPhone 7, it gets very hot.

**Comment by hth** [comment]
Encountered similar issue. Is there any solution? Any likelihood of this getting resolved anytime soon?

**Comment by zhxf2012** [comment]
Maybe you can use old version 3.1.0  which is fast and dosn't get hot.

**Comment by hth** [comment]
I can certainly try that. Will provide feed back.

**Comment by hth** [comment]
@zhxf2012 You were correct. Downgrading to 3.1.0 did help. Thanks!

**Comment by benjohnde** [comment]
The higher resolution of the sessionPreset may cause the need for additional calculations. I'm going to deep dive into that before the next release.

**Comment by just4eternity** [comment]
Facing the same problem with the current release 3.2.2, do you have some news to share about this ?
thanks

**Comment by freezy7** [comment]
@benjohnde I found a way to reduce CPU usage and eventually reduce CPU usage by around 30%.

Add the following code to the `AVCaptureVideoDataOutputSampleBufferDelegate`.
```objc
- (void)captureOutput:(AVCaptureOutput *)captureOutput
didOutputSampleBuffer:(CMSampleBufferRef)sampleBuffer
       fromConnection:(AVCaptureConnection *)connection {

     ...
    // ready code

    // Capture 3 frames per second or customize them.
    float captureFramesPerSec = 3.0f;
    float kMinMargin = 1.0 / self.captureFramesPerSec;
    
    // Gets the timestamp for each frame.
    CMTime presentTimeStamp = CMSampleBufferGetPresentationTimeStamp(sampleBuffer);
    
    static double curFrameTimeStamp = 0;
    static double lastFrameTimeStamp = 0;
    
    curFrameTimeStamp = (double)presentTimeStamp.value / presentTimeStamp.timescale;
    
    if (curFrameTimeStamp - lastFrameTimeStamp > kMinMargin) {
        lastFrameTimeStamp = curFrameTimeStamp;
        
        CVImageBufferRef videoFrame = CMSampleBufferGetImageBuffer(sampleBuffer);
        CGImageRef videoFrameImage = [ZXCGImageLuminanceSource createImageFromBuffer:videoFrame];
        CGImageRef rotatedImage = [self createRotatedImage:videoFrameImage degrees:self.rotation];
        CGImageRelease(videoFrameImage);
        
        ......
        //then decoding
    }

}
```

This reduces the utilization of the parsed images per second, thereby reducing CPU usage.

**Comment by benjohnde** [comment]
We could use that as some `skipFrames` option.

**Comment by freezy7** [comment]
@benjohnde ok, I will make it today.

**Comment by benjohnde** [comment]
Nice to hear that 🎉 !
