### ISSUE TITLE
scan result O16103106156   but 016103106156 is right

### ISSUE THREAD

**Issue by LvCode** [TheLevelUp/ZXingObjC#315]
![image](https://cloud.githubusercontent.com/assets/16863736/20087344/9913e000-a5b2-11e6-8ff2-9bd453796149.png)
![image](https://cloud.githubusercontent.com/assets/16863736/20087400/10bd31a6-a5b3-11e6-8c13-9c0c7e3435e2.png)

There are some problems，scan result O is wrong. 0 is right.Waiting for your message

**Comment by benjohnde** [comment]
Seems like manatee and scandit make the same mistake. Maybe your barcode is wrong?

**Comment by LvCode** [comment]
Thank you answer question！
It‘s my fault，my barcode is wrong.
Thanks again
