### ISSUE TITLE
Terminated due to memory issue

### ISSUE THREAD

**Issue by mahin8514** [TheLevelUp/ZXingObjC#322]
`- (void)captureResult:(ZXCapture *)capture result:(ZXResult *)result {
    
    if (!result) return;
    CGAffineTransform inverse = CGAffineTransformInvert(_captureSizeTransform);
	NSMutableArray *points = [[NSMutableArray alloc] init];
	NSString *location = @"";
	for (ZXResultPoint *resultPoint in result.resultPoints) {
		CGPoint cgPoint = CGPointMake(resultPoint.x, resultPoint.y);
		CGPoint transformedPoint = CGPointApplyAffineTransform(cgPoint, inverse);
		transformedPoint = [self.scanRectView convertPoint:transformedPoint toView:self.scanRectView.window];
		NSValue* windowPointValue = [NSValue valueWithCGPoint:transformedPoint];
		location = [NSString stringWithFormat:@"%@ (%f, %f)", location, transformedPoint.x, transformedPoint.y];
		[points addObject:windowPointValue];
	}

     NSString *formatString = [self barcodeFormatToString:result.barcodeFormat];
     NSString *display = [NSString stringWithFormat:@"Scanned!\n\nFormat: %@\n\nContents:\n%@\nLocation: %@", formatString, result.text, location];
     NSLog(@"%@", display);
     [self.decodedLabel performSelectorOnMainThread:@selector(setText:) withObject:display waitUntilDone:YES];

     AudioServicesPlaySystemSound(kSystemSoundID_Vibrate);

    [self.capture stop];
    
     ResultViewController *resultVC = [self.storyboard instantiateViewControllerWithIdentifier:@"resultID"];
     resultVC.resultContentHolder = result.text;
     [self.navigationController pushViewController:resultVC animated:YES];
  }
`

Here is the code used by me. After capturing the result i tried to push to another viewcontroller. It worked. But after trying 3-4 times the app terminates with this exception. The memory usage is too high. And also the result is captured more than once still `[self.capture stop];` used in my code

**Comment by benjohnde** [comment]
Could you post the whole ViewController? Some CoreGraphics invocations need some separate `@autoreleasepool` wrapping. You may also forgot to release some memory allocations?

Have you tried to track the memory consumption via Instruments?

**Comment by mahin8514** [comment]
I used the same code of sample project provided by ZXing in my ViewController.
Having a problem that capturing occurs multiple times after getting result too.

```


#import <AudioToolbox/AudioToolbox.h>
#import "ViewController.h"
#import "ResultViewController.h"

@interface ViewController ()

@property (nonatomic, strong) ZXCapture *capture;
@property (nonatomic, weak) IBOutlet UIView *scanRectView;

@end

@implementation ViewController {
	CGAffineTransform _captureSizeTransform;
}

#pragma mark - View Controller Methods

- (void)dealloc {
  [self.capture.layer removeFromSuperlayer];
}

- (void)viewDidLoad {
  [super viewDidLoad];

  self.capture = [[ZXCapture alloc] init];
  self.capture.camera = self.capture.back;
  self.capture.focusMode = AVCaptureFocusModeContinuousAutoFocus;
  

  [self.view.layer addSublayer:self.capture.layer];

  [self.view bringSubviewToFront:self.scanRectView];
}

- (void)viewWillAppear:(BOOL)animated {
  [super viewWillAppear:animated];

  
  self.capture.delegate = self;

  [self applyOrientation];
   
}



- (BOOL)shouldAutorotateToInterfaceOrientation:(UIInterfaceOrientation)toInterfaceOrientation {
  return toInterfaceOrientation == UIInterfaceOrientationPortrait;
}

- (void)didRotateFromInterfaceOrientation:(UIInterfaceOrientation)fromInterfaceOrientation {
	[super didRotateFromInterfaceOrientation:fromInterfaceOrientation];
	[self applyOrientation];
}

- (void)viewWillTransitionToSize:(CGSize)size withTransitionCoordinator:(id <UIViewControllerTransitionCoordinator>)coordinator {
	[super viewWillTransitionToSize:size withTransitionCoordinator:coordinator];
	[coordinator animateAlongsideTransition:^(id<UIViewControllerTransitionCoordinatorContext> context) {
	} completion:^(id<UIViewControllerTransitionCoordinatorContext> context)
	{
		[self applyOrientation];
	}];
}

#pragma mark - Private
- (void)applyOrientation {
	UIInterfaceOrientation orientation = [[UIApplication sharedApplication] statusBarOrientation];
	float scanRectRotation;
	float captureRotation;

	switch (orientation) {
		case UIInterfaceOrientationPortrait:
			captureRotation = 0;
			scanRectRotation = 90;
			break;
		case UIInterfaceOrientationLandscapeLeft:
			captureRotation = 90;
			scanRectRotation = 180;
			break;
		case UIInterfaceOrientationLandscapeRight:
			captureRotation = 270;
			scanRectRotation = 0;
			break;
		case UIInterfaceOrientationPortraitUpsideDown:
			captureRotation = 180;
			scanRectRotation = 270;
			break;
		default:
			captureRotation = 0;
			scanRectRotation = 90;
			break;
	}
	[self applyRectOfInterest:orientation];
	CGAffineTransform transform = CGAffineTransformMakeRotation((CGFloat) (captureRotation / 180 * M_PI));
	[self.capture setTransform:transform];
	[self.capture setRotation:scanRectRotation];
	self.capture.layer.frame = self.view.frame;
}

- (void)applyRectOfInterest:(UIInterfaceOrientation)orientation {
	CGFloat scaleVideo, scaleVideoX, scaleVideoY;
	CGFloat videoSizeX, videoSizeY;
	CGRect transformedVideoRect = self.scanRectView.frame;
	if([self.capture.sessionPreset isEqualToString:AVCaptureSessionPreset1920x1080]) {
		videoSizeX = 1080;
		videoSizeY = 1920;
	} else {
		videoSizeX = 720;
		videoSizeY = 1280;
	}
	if(UIInterfaceOrientationIsPortrait(orientation)) {
		scaleVideoX = self.view.frame.size.width / videoSizeX;
		scaleVideoY = self.view.frame.size.height / videoSizeY;
		scaleVideo = MAX(scaleVideoX, scaleVideoY);
		if(scaleVideoX > scaleVideoY) {
			transformedVideoRect.origin.y += (scaleVideo * videoSizeY - self.view.frame.size.height) / 2;
		} else {
			transformedVideoRect.origin.x += (scaleVideo * videoSizeX - self.view.frame.size.width) / 2;
		}
	} else {
		scaleVideoX = self.view.frame.size.width / videoSizeY;
		scaleVideoY = self.view.frame.size.height / videoSizeX;
		scaleVideo = MAX(scaleVideoX, scaleVideoY);
		if(scaleVideoX > scaleVideoY) {
			transformedVideoRect.origin.y += (scaleVideo * videoSizeX - self.view.frame.size.height) / 2;
		} else {
			transformedVideoRect.origin.x += (scaleVideo * videoSizeY - self.view.frame.size.width) / 2;
		}
	}
	_captureSizeTransform = CGAffineTransformMakeScale(1/scaleVideo, 1/scaleVideo);
	self.capture.scanRect = CGRectApplyAffineTransform(transformedVideoRect, _captureSizeTransform);
}

#pragma mark - Private Methods

- (NSString *)barcodeFormatToString:(ZXBarcodeFormat)format {
  switch (format) {
    case kBarcodeFormatAztec:
      return @"Aztec";

    case kBarcodeFormatCodabar:
      return @"CODABAR";

    case kBarcodeFormatCode39:
      return @"Code 39";

    case kBarcodeFormatCode93:
      return @"Code 93";

    case kBarcodeFormatCode128:
      return @"Code 128";

    case kBarcodeFormatDataMatrix:
      return @"Data Matrix";

    case kBarcodeFormatEan8:
      return @"EAN-8";

    case kBarcodeFormatEan13:
      return @"EAN-13";

    case kBarcodeFormatITF:
      return @"ITF";

    case kBarcodeFormatPDF417:
      return @"PDF417";

    case kBarcodeFormatQRCode:
      return @"QR Code";

    case kBarcodeFormatRSS14:
      return @"RSS 14";

    case kBarcodeFormatRSSExpanded:
      return @"RSS Expanded";

    case kBarcodeFormatUPCA:
      return @"UPCA";

    case kBarcodeFormatUPCE:
      return @"UPCE";

    case kBarcodeFormatUPCEANExtension:
      return @"UPC/EAN extension";

    default:
      return @"Unknown";
  }
}

#pragma mark - ZXCaptureDelegate Methods

- (void)captureResult:(ZXCapture *)capture result:(ZXResult *)result {
    
    if (!result) return;
    CGAffineTransform inverse = CGAffineTransformInvert(_captureSizeTransform);
	NSMutableArray *points = [[NSMutableArray alloc] init];
	NSString *location = @"";
	for (ZXResultPoint *resultPoint in result.resultPoints) {
		CGPoint cgPoint = CGPointMake(resultPoint.x, resultPoint.y);
		CGPoint transformedPoint = CGPointApplyAffineTransform(cgPoint, inverse);
		transformedPoint = [self.scanRectView convertPoint:transformedPoint toView:self.scanRectView.window];
		NSValue* windowPointValue = [NSValue valueWithCGPoint:transformedPoint];
		location = [NSString stringWithFormat:@"%@ (%f, %f)", location, transformedPoint.x, transformedPoint.y];
		[points addObject:windowPointValue];
	}


  // We got a result. Display information about the result onscreen.
   NSString *formatString = [self barcodeFormatToString:result.barcodeFormat];
   NSString *display = [NSString stringWithFormat:@"Scanned!\n\nFormat: %@\n\nContents:\n%@\nLocation: %@", formatString, result.text, location];
   NSLog(@"%@", display);
  // Vibrate
   AudioServicesPlaySystemSound(kSystemSoundID_Vibrate);

   [self.capture stop];
        
   ResultViewController *resultVC = [self.storyboard instantiateViewControllerWithIdentifier:@"resultID"];
   resultVC.resultContentHolder = result.text;
   [self.navigationController pushViewController:resultVC animated:YES];   
}


@end

```

**Comment by benjohnde** [comment]
- I never ran into that issue because I use my own ZXCapture implementation. I will deep dive into that later on.
- Multiple results can be caused as ZXingObjC invokes your ZXCaptureDelegate method every time it recognizes a result. You can fix that with a simple boolean state (for instance `if (isFinished) return; isFinished = true;`).

**Comment by mahin8514** [comment]
I updated it with boolean state. multiple pushing to ViewController solved. Application termination still occurring due to high memory usage.

**Comment by benjohnde** [comment]
Do you have any footprint / console / debugger which gives you any insight what exactly causes the high memory usage?

**Comment by benjohnde** [comment]
Does the high memory consumption also occur when using the example project?

**Comment by mahin8514** [comment]
No. In example project no pushing to another ViewController. While pushing to another ViewController this problem occurs. Thinks that ZXCapture not releasing from memory while pushing.

**Comment by mahin8514** [comment]
And also the pushed new ViewController has no further codes.

**Comment by benjohnde** [comment]
Ah okay, I see! And after pushing the ResultVC on the current Stack, you pop the ResultVC to scan again? Or do you push a new initialized ViewController instead? Just so get a feeling of your app-flow.

If your app-flow is the latter one, the ViewController wouldn't get garbage collected (i.e. the ARC will decrease and release all memory). Then I would redesign some parts of your current ViewController and just pop.

For the former one, I didn't see a line which could leak to a memory leak.

**Comment by mahin8514** [comment]
Flow is like ResultVC only displays the result.text in a simple label. There is only 3 VC. OpeningVC, ScanningVC and ResultVC. Stack begins from openingVC. From there ScanningVC is pushed. After scan ResultVC is pushed. From ResultVC i pushed to OpeningVC again by a segue.(Tried code too. `[self.navigationController pushViewController:openingVC animated:YES];`). after this Debug Navigator shows high memory. Again this whole process continued and after 4-5 scan this error is shown and app terminates

**Comment by benjohnde** [comment]
Yeah this is exactly what I guessed.

By doing that, the navigation stack gets filled with ScanningVC and they never get released. Thus, more and more memory is consumed. In addition, your `dealloc` method will never be invoked at all. The right order would be, to pop the Result VC if you want to scan again (in this small scenario).

What may help you out for now, try to change this:

```objc
- (void)dealloc {
  [self.capture.layer removeFromSuperlayer];
}

- (void)viewDidLoad {
  [super viewDidLoad];
  self.capture = [[ZXCapture alloc] init];
  self.capture.camera = self.capture.back;
  self.capture.focusMode = AVCaptureFocusModeContinuousAutoFocus;
  [self.view.layer addSublayer:self.capture.layer];
  [self.view bringSubviewToFront:self.scanRectView];
}

- (void)viewWillAppear:(BOOL)animated {
  [super viewWillAppear:animated];
  self.capture.delegate = self;
  [self applyOrientation];
}
```

into that:

```objc
- (void)viewDidLoad {
  [super viewDidLoad];
  self.capture = [[ZXCapture alloc] init];
  self.capture.camera = self.capture.back;
  self.capture.focusMode = AVCaptureFocusModeContinuousAutoFocus;
  [self.view.layer addSublayer:self.capture.layer];
  [self.view bringSubviewToFront:self.scanRectView];
}

- (void)viewWillAppear:(BOOL)animated {
  [super viewWillAppear:animated];
  self.capture.delegate = self;
  [self applyOrientation];
}

- (void)viewDidDisappear:(BOOL)animated {
  // release memory as VC will not be reused
  [super viewDidDisappear:animated];
  [self.capture.layer removeFromSuperlayer];
  self.capture = nil;
}
```

This may release some memory. But I would guess it will crash again after some time, as your navigationStack gets flooded with new VCs and never has a change to release memory.

Cheers!
Ben John.
