### ISSUE TITLE
pod install failed

### ISSUE THREAD

**Issue by wpen** [TheLevelUp/ZXingObjC#331]
platform :ios, '7.0'
    pod 'ZXingObjC', '~> 3.2.1'

Analyzing dependencies
[!] Unable to satisfy the following requirements:

- `ZXingObjC (~> 3.2.1)` required by `Podfile`

Specs satisfying the `ZXingObjC (~> 3.2.1)` dependency were found, but they required a higher minimum deployment target.

**Comment by benjohnde** [comment]
Sry deployment target is currently set to 8.0.
