### ISSUE TITLE
Cannot recongize most QrCode for 3.2.0 and 3.2.1

### ISSUE THREAD

**Issue by zhxf2012** [TheLevelUp/ZXingObjC#332]
xcode 8.1  version 3.2 and version 3.2.1  cannot recongize most QrCode (maybe just too slow to get the result)  and device get hot  .While version 3.1.0 dose well.

**Comment by HalfOfSunshine** [comment]
don't set scanRect well be OK

**Comment by HalfOfSunshine** [comment]
I can't t recongize too

**Comment by marcuswu0814** [comment]
@HalfOfSunshine Helpful information, but anyone know why?

**Comment by benjohnde** [comment]
Closing this in favor of #334.
