### ISSUE TITLE
Encoded QR and Aztec barcodes contain blur/dither

### ISSUE THREAD

**Issue by adil-hussain-84** [TheLevelUp/ZXingObjC#335]
I'm generating QR and Aztec barcodes in an iOS application using the latest version (3.2.1) of this library. I'm doing so using code identical to the library's "Encoding" example, i.e:

    NSError *error = nil;
    ZXMultiFormatWriter *writer = [ZXMultiFormatWriter writer];
    ZXBitMatrix* result = [writer encode:@"A string to encode"
                                  format:kBarcodeFormatQRCode
                                  width:200
                                  height:200
                                  error:&error];

    CGImageRef imageRef = [[ZXImage imageWithMatrix:result] cgimage];
    UIImage *image = [UIImage imageWithCGImage:imageRef];
    myImageView.image = image;

However, I see that the barcode which is rendered in my `UIImageView` using the above code contains some blur/dither when transitioning from a black block to a white block. This is undesirable and could impact scanning speed in an environment where scanning speed is top-priority. Here is an example of the barcode zoomed in to make the problem more apparent:

![screenshot ios qr](https://cloud.githubusercontent.com/assets/17025131/25440283/ea7f3b56-2a96-11e7-9452-e0175b387135.png)

**Question:** Is there anything additional I can do when generating/rendering the barcodes in my iOS application to avoid this blur/dither??

Note that I have specified my `UIImageView`'s Content Mode to be Center ([UIViewContentModeCenter](https://developer.apple.com/reference/uikit/uiviewcontentmode/uiviewcontentmodecenter)) so that it doesn't scale the contained image and thus I can't imagine the `UIImageView` causing the blur/dither. 

As an aside: I'm using the equivalent `com.google.zxing:core:3.3.0` library in an Android application and I'm _not_ seeing the same problem there. See zoomed in screenshot of the barcode below from the Android application:

![screenshot android qr](https://cloud.githubusercontent.com/assets/17025131/25440382/381c001a-2a97-11e7-8501-68d981a9bccc.png)

**Comment by adil-hussain-84** [comment]
After testing this on a couple of other devices (iPhone 5s and iPhone 7) I've come to the realisation that this is an issue specific to the iPhone 6+. Turns out that the "physical" resolution (1080 x 1920 px) of the iPhone 6+ is smaller than the "virtual" resolution (1242 x 2208 px) (see [here](https://www.paintcodeapp.com/news/ultimate-guide-to-iphone-resolutions)) and thus the iPhone 6+ does some downsampling of the display and this is what is causing the blur/dither. Sadly I don't think there is anything that can be done about this... unless anyone has any suggestions??

**Comment by benjohnde** [comment]
I may have time to answer you in more detail tomorrow.

IIRC you have to rescale the image properly, for instance:
```objc
- (UIImage *)upscaleQRCode:(UIImage *)image
{
    return [self resizeImage:image withQuality:kCGInterpolationNone rate:16.0];
}

- (UIImage *)resizeImage:(UIImage *)image withQuality:(CGInterpolationQuality)quality rate:(CGFloat)rate
{
    UIImage *resized = nil;
    CGFloat width = image.size.width * rate;
    CGFloat height = image.size.height * rate;
    
    UIGraphicsBeginImageContext(CGSizeMake(width, height));
    CGContextRef context = UIGraphicsGetCurrentContext();
    CGContextSetInterpolationQuality(context, quality);
    [image drawInRect:CGRectMake(0, 0, width, height)];
    resized = UIGraphicsGetImageFromCurrentImageContext();
    UIGraphicsEndImageContext();
    
    return resized;
}
```

Cheers!

**Comment by benjohnde** [comment]
Small extra note: the trick is to ignore scaling of the `UIImageView` completely and resize the qr code to the actual size of the `UIImageView`!

**Comment by benjohnde** [comment]
@adil-hussain-84 does it work?

**Comment by adil-hussain-84** [comment]
@benjohnde: Sorry for the late response. I haven't tried this yet but I believe scaling the barcode to the exact size of the `UIImageView` would be problematic since this would scale the barcode by a non-integer factor (which causes the blur/dither). Also, unless I'm missing something I can't see that your code snippet would protect against the iPhone 6+ downsampling which I've found to be the root cause of my blue/dither problem (see my previous comment). What do you think?

Thank you btw for your help. Appreciate it.
