### ISSUE TITLE
QRImage Not Decode! ERROR:1002 "A barcode was not found in this image" 

### ISSUE THREAD

**Issue by minjoongkim** [TheLevelUp/ZXingObjC#338]
The library is always appreciated.
It is used when decoding QR images.
It is a very convenient library.
But there is a problem.

Do not Decode some QRImage.

Success Decode Image = https://www.dropbox.com/s/joparwm4vp6ofrs/qr2.png?dl=1
Error Decode Image = https://www.dropbox.com/s/a1vezc2vxzms4bq/qr1.png?dl=1

ErrorMessage = Error Domain=ZXErrorDomain Code=1002 "A barcode was not found in this image" UserInfo={NSLocalizedDescription=A barcode was not found in this image}

But There is certainly QRImage in the image. 

Check for my message.
Thank you.
---------------------------------------------------------------------------------------------------
My Source :
CGImageRef imageToDecode;  // Given a CGImage in which we are looking for barcodes

ZXLuminanceSource *source = [[[ZXCGImageLuminanceSource alloc] initWithCGImage:imageToDecode] autorelease];
ZXBinaryBitmap *bitmap = [ZXBinaryBitmap binaryBitmapWithBinarizer:[ZXHybridBinarizer binarizerWithSource:source]];

NSError *error = nil;

// There are a number of hints we can give to the reader, including
// possible formats, allowed lengths, and the string encoding.
ZXDecodeHints *hints = [ZXDecodeHints hints];

ZXMultiFormatReader *reader = [ZXMultiFormatReader reader];
ZXResult *result = [reader decode:bitmap
                            hints:hints
                            error:&error];
if (result) {
  // The coded result as a string. The raw data can be accessed with
  // result.rawBytes and result.length.
  NSString *contents = result.text;

  // The barcode format, such as a QR code or UPC-A
  ZXBarcodeFormat format = result.barcodeFormat;
} else {
  // Use error to determine why we didn't get a result, such as a barcode
  // not being found, an invalid checksum, or a format inconsistency.
}

**Comment by minjoongkim** [comment]
I found something strange.
200x200 size image can not be converted.
However, 100x100 size images will be converted.
What is the optimal size?

**Comment by benjohnde** [comment]
Maybe you can add `tryHarder` to the `hints`.
