### ISSUE TITLE
iOS - scanning from web pages

### ISSUE THREAD

**Issue by emdewu** [TheLevelUp/ZXingObjC#342]
Have a question regarding BarcodeScanner - An iOS application that captures video from the camera, scans for barcodes and displays results on screen - https://github.com/TheLevelUp/ZXingObjC
Is there any possibility to use this application in the middle of the flow of my webApp. 
It's means, I would like to invoke scaner successfully from my webpage, scans the barcode and sends the code back to same(current) web-page.

Please for any suggestions for this solution.

There is also information on https://github.com/zxing/zxing/wiki/Scanning-From-Web-Pages that:
"Note that this functionality will be available on the iPhone app Barcodes. iOS works differently, and so the URL pattern must instead use the zxing://scan/ URL"
Problem is, that I can't find the Barcodes application in App Store.

Thank you in advance for your help,

**Comment by benjohnde** [comment]
To invoke the scanner, you should use a URL scheme for your application, you can read more on that [here](https://developer.apple.com/library/content/featuredarticles/iPhoneURLScheme_Reference/Introduction/Introduction.html).

To send the code back the current web-page, you could use some javascript magic as well as sending another web request with the received / scanned code.
