### ISSUE TITLE
ZXing Objectivec can't generator image barcode's ean-13 format!

### ISSUE THREAD

**Issue by lydo** [TheLevelUp/ZXingObjC#343]
Please help me!. 
I use this to generator image barcode ean-13 format, result is not! It keeps checking "Contents do not pass checksum" errors

NSError *error = nil;
ZXMultiFormatWriter *writer = [ZXMultiFormatWriter writer];
ZXBitMatrix* result = [writer encode:@"4334567841243"
                              format:kBarcodeFormatEan13
                               width:500
                              height:500
                               error:&error];
if (result) {
  CGImageRef image = [[ZXImage imageWithMatrix:result] cgimage];

  // This CGImageRef image can be placed in a UIImage, NSImage, or written to a file.
} else {
  NSString *errorMessage = [error localizedDescription];
}

**Comment by benjohnde** [comment]
Your EAN13 code is not valid and does not surpass the internal validator. For more information compare http://formvalidation.io/validators/ean/.
