### ISSUE TITLE
New release/tag for xcode 9 support?

### ISSUE THREAD

**Issue by BobElDevil** [TheLevelUp/ZXingObjC#355]
Just leaving a minor request for a version bump, so we can specify a semantic version with carthage that compiles in Xcode 9. The fixes for the compiler errors are already in master, there's just no release for it yet.

Currently we are working around it by pointing at the master branch instead of a version specifier in the Cartfile.

**Comment by xudafeng** [comment]
xcode 9 bump too,

```
/Library/Caches/org.carthage.CarthageKit/DerivedData/9.0_9A235/ZXingObjC/3.2.1/Build/Intermediates.noindex/ArchiveIntermediates/iOS\ Framework/IntermediateBuildFilesPath/ZXingObjC.build/Release-iphoneos/iOS\ Framework.build/Objects-normal/armv7/ZXByteArray.o ZXingObjC/common/ZXByteArray.m normal armv7 objective-c com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)
Build Failed

```

**Comment by benjohnde** [comment]
Sry for being late, should work with 3.2.2.
