### ISSUE TITLE
Does this correspond to iOS11 (arm64)?

### ISSUE THREAD

**Issue by TTSUZUKIA** [TheLevelUp/ZXingObjC#357]
Does this correspond to iOS11 (arm64)?

**Comment by michaelkirk** [comment]
> Does this correspond to iOS11 (arm64)?

Can you clarify your question? 

This library does work with iOS11/arm64, but you may need to specify to use head of master since there hasn't yet been an official release compatible with  XCode9.

**Comment by benjohnde** [comment]
Just created the release of 3.2.2. This version should work with Xcode 9.
