### ISSUE TITLE
Large datamatrix codes with many characters

### ISSUE THREAD

**Issue by ambuDevs** [TheLevelUp/ZXingObjC#358]
Hello,

i am trying to encode a large string into a data matrix barcode. Unfortunately it is not working - meaning a barcode is created but it cannot be scanned by any scanning application including zxing scanner. I tried shorter strings and it seems to work with less characters. Is there a formatting that I need to apply or something else that i forgot?

let data = "<MP v=\"024\" U=\"B544B6976AB84E3498AA96D8E6FA29C1\" l=\"de-DE\"><P g=\"Michaela\" f=\"Musterhausen\" egk=\"P123456789\" b=\"19361213\" t=\"Dr.\" v=\"von\" z=\"Freifrau\"/><A n=\"Dr. Manfred Uberall\" s=\"Hauptstraße 55\" z=\"01234\" c=\"Am Ort\" p=\"04562-12345\" e=\"m.ue@praxis-ueberall.de\" t=\"2017-05-02T12:00:00\"/><O/><S><M p=\"4213974\" m=\"1\" du=\"1\" i=\"wahrend der Mahlzeiten\" r=\"Bluthochdruck\"/><M p=\"6453174\" m=\"1\" du=\"1\" i=\"wahrend der Mahlzeiten\" r=\"Bluthochdruck\"/><M p=\"4129423\" v=\"1\" du=\"1\" i=\"wahrend der Mahlzeiten\" r=\"art. Verschluss\"/><M p=\"1048888\" v=\"1\" du=\"1\" i=\"nach der Mahlzeit\" r=\"erhohte Blutfette\"/></S><S c=\"416\"><M p=\"544757\" m=\"20\" v=\"10\" du=\"p\" i=\"subkutan\" r=\"Diabetes\"/></S><S c=\"411\"><M p=\"4877970\" t=\"max. 3\" du=\"5\" i=\"akut\" r=\"Herzschmerzen\"/><M p=\"2083906\" h=\"1\" du=\"1\" i=\"bei Bedarf\" r=\"Schlaflosigkeit\"/></S><S c=\"422\"><X t=\"Bitte messen Sie Ihren Blutdruck taglich!\"/></S></MP>"

ZXDataMatrixWriter *writer = [[ZXDataMatrixWriter alloc] init];
ZXBitMatrix *result = [writer encode:data
                                format:kBarcodeFormatDataMatrix
                                 width:2000
                                height:2000
                                 error:nil];

**Comment by benjohnde** [comment]
Did you try to escape the sequence? Did you read the specs of datamatrix, so your amount of characters is still according to spec?

**Comment by ambuDevs** [comment]
Yes, i tried a shorter sequence (that is working) and escape the sequence. To be honest, this is the content of a datamatrix barcode that I read into the system (with the library) and at the same time wanted to used the content as basis for the new barcode. Reading the barcode is not a problem but putting the content in a new barcode failed.

**Comment by benjohnde** [comment]
Did you try zxing/zxing?
