### ISSUE TITLE
application not run in iOS 11

### ISSUE THREAD

**Issue by niravkotecha** [TheLevelUp/ZXingObjC#362]
File:- `ZXByteArray.m` File
Method:- `- (id)initWithBytes:(int8_t)byte1, ...`
line:- `va_start(args, byte1);`
Error:- **passing an object that undergoes default argument promotion to 'va_start' has undefined behavior**

This error is coming in Zxing Library From Xcode 9 and iOS 11.
Please check it.

**Comment by niravkotecha** [comment]
@benjohnde please check it because i can't run in iOS 11

**Comment by benjohnde** [comment]
I'm currently diving into that.

**Comment by benjohnde** [comment]
Can not reproduce unter iOS 11 / Xcode 9 with the current version.
