### ISSUE TITLE
EAN-13 BUG

### ISSUE THREAD

**Issue by MartinPrusa** [TheLevelUp/ZXingObjC#363]
Is it possible, to support this version of EAN-13? I am unable to read it on iOS 11.1 with iPhone 6S Plus.

Regards,
-Martin

<img width="944" alt="screen shot 2017-11-02 at 23 31 44" src="https://user-images.githubusercontent.com/1409050/32353996-04df6706-c028-11e7-8787-439dea35a045.png">

**Comment by benjohnde** [comment]
![image](https://user-images.githubusercontent.com/5439810/32363412-910c5350-c06f-11e7-9e1b-f45696385bd1.png)

Your barcode is incorrect.
