### ISSUE TITLE
Can't stop ZXCapture when delegate is set

### ISSUE THREAD

**Issue by ethan-gerardot** [TheLevelUp/ZXingObjC#364]
I have a scanner view controller inside a tab bar controller. The scanner VC has a ZXCapture reference. I instantiate it on viewDidLoad (which gets called once because of the tab bar controller) and set delegate = self (which starts the capture running, which seems odd but oh well). On viewWillDisappear, I call capture.stop. Which works fine, it seems. But then on viewDidDisappear, inexplicably the capture somehow is running again, even though I never told it start again (I know because I log capture.running).

If I comment out the line to set delegate = self in viewDidLoad, then this doesn't happen...I can start and the stop the capture as expected (but then of course I can't get the captured results if I'm not the delegate, so that would be useless).

It seems that if the delegate isn't nil, stop won't work because the capture will just get restarted somehow.

This is very strange and I'm not sure what's going on. Just to emphasize, **the only line I change is setting the delegate to self in viewDidLoad.**

NOTE: I noticed that in the case where I set delegate = self then ZXCapture's captureOutput:didOutputSampleBuffer:fromConnection: method never stops getting called even when I navigate away from the scanner VC and tell the capture to stop. But in the case where I don't set delegate = self, then that method only gets called while in the scanner VC and capture is running (which is what I would expect).

**Comment by ethan-gerardot** [comment]
My current work around is to set delegate = self before calling [self.capture start] in viewWillAppear and set delegate = nil before calling [self.capture stop] in viewWillDisappear.

**Comment by InnaLMC** [comment]
@ethan-gerardot  This fix works for me too, thanks

**Comment by benjohnde** [comment]
`ZXCapture` is pretty old. The fix is okay. The example should be rewritten in Swift.
