### ISSUE TITLE
While generating UPC-A bar code generation, facing issues with 12 digit code 

### ISSUE THREAD

**Issue by vaibhavTesting** [TheLevelUp/ZXingObjC#368]
Hi Sir's,

We are working for create UPC-A bar code and facing issues with 12 digit code in your Objective c iPhone sdk.
e.g code is : 98765401762
We are facing this error "Contents do not pass checksum"
Please suggest to fix this issue.

**Comment by eassy** [comment]
you can insert 0 to the generated code as the first number, than try again
