### ISSUE TITLE
Anyone there

### ISSUE THREAD

**Issue by FahdSaif** [TheLevelUp/ZXingObjC#370]
Hi, is anyone there in the ZXING support team?

**Comment by FahdSaif** [comment]
am i speaking to the creators of ZXING?

**Comment by benjohnde** [comment]
The code ist mostly transpiled from zxing/zxing, which was initially created by Google (?). This project here was created by TheLevelUp and I am like the last warrior standing to provide at least some support. I am also trying to fix some of the most urgent bugs.

**Comment by FahdSaif** [comment]
thanks for replying. Understood bro.
