### ISSUE TITLE
2D Matrix inverted mixed modes

### ISSUE THREAD

**Issue by myfreepost** [TheLevelUp/ZXingObjC#371]
when setting inverted=true property, axing no longer looks for normal 2d matrix codes. is there a property for mixed mode (i.e. scan either inverted or normal code)? if not, does anyone have idea of how to configure this in zxing?

**Comment by benjohnde** [comment]
Do you mean the `invert` property within `ZXCapture`? It basically just inverts the LuminanceSource, so shouldn't react in "no longer looking for normal 2d matrix codes". Maybe your barcode does not work in inverted mode, then you could look for both, inverted and normal mode.

All you need to look at is here: https://github.com/TheLevelUp/ZXingObjC/blob/35811c5cf6f1d01974c307c8b23900d9cc03437b/ZXingObjC/client/ZXCapture.m#L386.
