### ISSUE TITLE
multiple barcodes doesn't work in Swift 4.0 n Xcode 9.2

### ISSUE THREAD

**Issue by himanshupadia** [TheLevelUp/ZXingObjC#372]
I use 'master' version (via CocoaPods) and this code (Xcode 9.2):
```
let source = ZXCGImageLuminanceSource(cgImage: tempImage.cgImage)
let bitmap = ZXBinaryBitmap(binarizer: ZXHybridBinarizer(source: source))
let hints = ZXDecodeHints()
hints.tryHarder = true
let reader = ZXMultiFormatReader()
let multiReader = ZXGenericMultipleBarcodeReader(delegate: reader)
do {
    let result = try multiReader!.decodeMultiple(bitmap, hints: hints)
    print(result)
} catch _ {
    print("Not found!")
}
```
It's not working for multiple barcode reading, every time is print "Not found!".
Single barcode is working fine but multiple not working.

Any help would we appreciated.
Thanks in advance.

**Comment by benjohnde** [comment]
@himanshupadia  Any example data, for instance the two (or multiple) barcodes you are trying to scan?

To your specific problem, you are invoking `decodeMultiple` with `ZXDecodeHints` with empty valid `barcodeFormats`. Hence, no barcode can be detected.

At first, I would try `decodeMultiple` with no hints set at all. Default behaviour can be seen here: [ZXMultiFormatReader.m#L107](https://github.com/TheLevelUp/ZXingObjC/blob/master/ZXingObjC/ZXMultiFormatReader.m#L107).

**Comment by himanshupadia** [comment]
@benjohnde thanks for reply, I will try and let you know.

**Comment by himanshupadia** [comment]
@benjohnde  thanks for help, above code is works, I think the barcode is unreadable which I was using.
