### ISSUE TITLE
invert color when creating DataMatrix barcode

### ISSUE THREAD

**Issue by alex52** [TheLevelUp/ZXingObjC#373]
Is it possible to create a DataMatrix barcode with inverted color? (white content)

Even better if it would be possible to do white content on transparent background.

**Comment by alex52** [comment]
I've been able to revert the colors using: + (ZXImage *)imageWithMatrix:(ZXBitMatrix *)matrix onColor:(CGColorRef)onColor offColor:(CGColorRef)offColor 

But no luck with the white or black content with transparent background, any idea how could I get the offColor transparent? Thanks!

**Comment by benjohnde** [comment]
Sure it is, and you already hit the right method. You can easily implement such a feature like being able to specify foreground and background colors.
