### ISSUE TITLE
Zxing - scanning issue for iOS application.

### ISSUE THREAD

**Issue by vishaldeshai** [TheLevelUp/ZXingObjC#375]
I am developing a iOS platform mobile application in which i have integrated zxing bar code library to scan barcodes.
The library works very well for the android application and but on iOS application the bar code detection is very poor (70% failure).

The same library working to scan the same bar code works very well on android but not on iOS.

Any kind of help or insight on the issue will be appreciable.

Thank you.

**Comment by benjohnde** [comment]
Use 720p. If that solves the failure rate (you can even apply a proper scanning rect and try to set `tryHarder=YES`) but the overall performance is still poor (in terms of cpu and memory usage), try to implement your own ZXCapture class.
