### ISSUE TITLE
ZXCaptureDelegate methods -- calling multiple times

### ISSUE THREAD

**Issue by kalyanpkumar** [TheLevelUp/ZXingObjC#378]
I see that this delegate method is being called multiple times after scanning is done.. 

 (void)captureResult:(ZXCapture *)capture result:(ZXResult *)result

**Comment by neacao** [comment]
@kalyanpkumar can you provide the sample project to reproduce this bug ?

**Comment by benjohnde** [comment]
That is kind of an async vs main thread thing. We could fix that with an additional `BOOL` and add some comments around it, so everybody gets the point.
