### ISSUE TITLE
ZXEncodeHints`s property margin do not work 

### ISSUE THREAD

**Issue by chaningcheng** [TheLevelUp/ZXingObjC#383]
i set margin property in order to remove the white edge, but it not work

**Comment by benjohnde** [comment]
Can you give some more information on that, maybe example code?

**Comment by benjohnde** [comment]
It should work, but you need to use it as following:

```objc
ZXEncodeHints *hints = [ZXEncodeHints hints];
hints.margin = [NSNumber numberWithInt:0];
```
