### ISSUE TITLE
The result of decoding pdf417 code is wrong.

### ISSUE THREAD

**Issue by unash** [TheLevelUp/ZXingObjC#385]
The string is: J090018900004751310097170889111928578075473
The encoded image is [here](https://barcode.tec-it.com/barcode.ashx?data=J090018900004751310097170889111928578075473&code=PDF417&multiplebarcodes=false&translate-esc=false&unit=Fit&dpi=96&imagetype=Gif&rotation=0&color=%23000000&bgcolor=%23ffffff&qunit=Mm&quiet=0).
Also, the image can be generated in the [website](https://barcode.tec-it.com/zh/PDF417?data=J090018900004751310097170889111928578075473).

However, when I use the demo on branch 'master', I get the result:
J090018900004751310097170889111928578000000

It seems that substring from 39th to the end will be set zero.

**Comment by benjohnde** [comment]
Could you test whether it is working with the Android BarcodeScanner Library zxing?

**Comment by benjohnde** [comment]
Confirmed to work in zxing/Zxing.

**Comment by benjohnde** [comment]
So we basically need a proper replacement for:
https://github.com/TheLevelUp/ZXingObjC/blob/7ef012605e469d5d701e22176becb73f4fa1ed8d/ZXingObjC/pdf417/encoder/ZXPDF417HighLevelEncoder.m#L394

and

https://github.com/TheLevelUp/ZXingObjC/blob/896a5cf96726003bae2e0487c17852479dde771b/ZXingObjC/pdf417/decoder/ZXPDF417DecodedBitStreamParser.m#L91

interesting though. I have an idea and will try that out.

**Comment by benjohnde** [comment]
https://github.com/TheLevelUp/ZXingObjC/blob/896a5cf96726003bae2e0487c17852479dde771b/ZXingObjC/pdf417/decoder/ZXPDF417DecodedBitStreamParser.m#L696

**Comment by benjohnde** [comment]
It is currently fixed in branch decimal-replacement.

**Comment by benjohnde** [comment]
@unash could you please verify that everything is working for you on the `decimal-replacement` branch? Here all tests are green :)

**Comment by benjohnde** [comment]
@unash is merged in master, I will create a new version.

**Comment by benjohnde** [comment]
Version will be `3.5.0`.
