### ISSUE TITLE
Detecting starting FNC1 symbol in code-128 barcodes

### ISSUE THREAD

**Issue by ant100984** [TheLevelUp/ZXingObjC#386]
Hello, i am currently having an issue with code-128 barcodes about starting FNC1 symbol (for GS1 barcodes). I don't seem to get that symbol in the scanned string in 'captureResult' delegate method. I am using the lib in iOS. Is there another way to detect GS1 barcodes? The same symbol is correctly read by the library if i scan the same barcode coded inside a DataMatrix barcode. Thanks.

**Comment by benjohnde** [comment]
Could you provide an example barcode?
