### ISSUE TITLE
Critical bug in ZXByteArray

### ISSUE THREAD

**Issue by benjohnde** [TheLevelUp/ZXingObjC#405]
In `ZXByteArray` the stop condition for iterating over potential arguments is variadic argument should be `-1`. This is not the case. Hence, if you emit only two bytes, you may result in an Array which contains those two bytes correctly, but tons of other randomly created bytes from the memory. In addition, the length obviously is also incorrect.

```objc
- (id)initWithBytes:(int)byte1, ... {
  va_list args;
  va_start(args, byte1);
  unsigned int length = 0;
  for (int8_t byte = byte1; byte != -1; byte = va_arg(args, int)) {
    length++;
  }
  va_end(args);

  if ((self = [self initWithLength:length]) && (length > 0)) {
    va_list args;
    va_start(args, byte1);
    int i = 0;
    for (int8_t byte = byte1; byte != -1; byte = va_arg(args, int)) {
      _array[i++] = byte;
    }
    va_end(args);
  }

  return self;
}
```

Potential fixes:
- Using NSMutableArray and the shorthand syntax (basically `arrayWithObjects` selector)
- Providing both, length and the bytes
- Something else...

**Comment by benjohnde** [comment]
Current workaround, but would be nicer to hand over an array.

```objc
- (id)initWithLength:(unsigned int)length bytes:(int)byte1, ... {
  if ((self = [self initWithLength:length]) && (length > 0)) {
    va_list args;
    va_start(args, byte1);
    _array[0] = (int8_t) byte1;
    for (int i = 1; i < length; i++) {
      int byte = va_arg(args, int);
      _array[i++] = (int8_t) byte;
    }
    va_end(args);
  }

  return self;
}
```

**Comment by benjohnde** [comment]
Can also be found in other elementary classes!

**Comment by benjohnde** [comment]
Ah nope, it is in general a problem if you are working with primitives as you can not check for nil. The condition `byte != -1` is not fulfilled.

**Comment by benjohnde** [comment]
Thus, you are leaking memory. More importantly: test can fail because the `[[ZXByteArray alloc] initWithBytes:-128,10];` will return `length > 2`. This shouldn't be the case.

**Comment by neacao** [comment]
👍

**Comment by benjohnde** [comment]
You could also just append `-1` in the end. But this is not always the case :)
