### ISSUE TITLE
Hard to detect customized qr code

### ISSUE THREAD

**Issue by neacao** [TheLevelUp/ZXingObjC#430]
Seems like with customized QR code. it's hard (can't) detect the information.
![qrcode-logo-design-starbucks](https://user-images.githubusercontent.com/16370568/46065911-95ad7800-c19d-11e8-90ee-460e4e2b5d23.png)

**Comment by benjohnde** [comment]
Have you tried it with zxing/zxing? Just curious.

**Comment by neacao** [comment]
Yeah, it can be decode by zxing. Result 
![Here](https://user-images.githubusercontent.com/16370568/46066107-153b4700-c19e-11e8-925a-7410aabd2b7f.png)

**Comment by benjohnde** [comment]
I will take a lot a your example.

**Comment by neacao** [comment]
:+1: lets me know if it's resolved, i will help to make more tests :D

**Comment by benjohnde** [comment]
Hmm I can decode it :)

**Comment by benjohnde** [comment]
How do you decode?

QRCode can be tricky with 1080p, you should utilise 720p.

And: do you use the current version 3.4.0 of ZXingObjC?

**Comment by benjohnde** [comment]
Perfect!

**Comment by benjohnde** [comment]
That's a difficult one. I believe the yellow is too bright. Could you double check of zxing/zxing is able to resolve this one. I would not really want to change much of the Binarizer logic. We can do little adjustments, but most importantly: is the barcode designed against the official spec?

**Comment by neacao** [comment]
No, it's not, actually the ZXingObjC can detect this one, but it takes a while before the yellow area can be converted to black.

**Comment by benjohnde** [comment]
I believe it depends on the angle of the camera, the environment, lighting, etc.

**Comment by neacao** [comment]
That's true, if I resize the image above smaller, the lib can decode it faster, so I would recommend about pyramid image processing, it means scale the image multiple size to detect the image

**Comment by neacao** [comment]
@benjohnde how do you think about scaling ?
**Problem**
1. Hard to detect QR code with large yellow area
2. Hard to detect small QR code
**Solution**
1. Scale image to x0.5, x1.0, x2.0 to decode
2. Those images will be process in concurrency mode
**Pros**
1. Resolved those ad-hoc cases
**Cons**
1. Cost of image scaling

**Comment by benjohnde** [comment]
I am not sure if the scaling resolves the problem you experience. I strongly believe that in your particular case, as you also stated, the Binarizer translates the yellow pixels into white ones. Maybe we could add a more loose Binarizer, when it comes to yellow pixels, to help you with those customized qr codes. We could add a toggle via `ZXDecodeHints`. Having said that, we would not alter code which is derived from zxing, but could add an alternative way for your cases in handling yellow pixels.

**Comment by benjohnde** [comment]
Even though scaling may lead to a different behaviour of binarizing, it strongly recommend that you would better stick to direct Binarizer adjustments.

**Comment by neacao** [comment]
Actually I have implemented those scaling image to see if the idea could work or not. Under x0.5, the yellow are could keep the black pixels & also image's feature, when x2.0 could decode the image w/out zooming. This is just an option can enable by user (or not).
You'r right, we should keep everything same as ZXing, but if we add more loose Binarizer, could it effect to other results of normal cases ? If not, can you provide some key points, so I can support to make another PR for this thing 😁

**Comment by neacao** [comment]
@benjohnde I found this doc 
> http://www.tannerhelland.com/3643/grayscale-image-algorithm-vb6

Could we use **Method 4 – Decomposition** using minimum values to convert grayscale. The goal is not a smooth grayscale image but better black/white pixels

**Comment by neacao** [comment]
I have make some tests with the image above & also normal cases, it works well, no need to scale image to resize the yellow area

**Comment by benjohnde** [comment]
Nice find @neacao! Love the drive. If all tests are passing, you can reach in a pull request or I may help out.

We could add some sort of additional `ZXDecodeHints` to reflect both, the difference to zxing and to let the user decide whether he wants to use additional processing 🤔.

**Comment by neacao** [comment]
@benjohnde I have found a better way to process, we could use `shades` of gray image to apply for each frame (Method 6), that's better because the `Min`'s formula might translate the background to black.
I will prepare another PR for this, but should I add `ZXDecodeHints` onto `ZXCGImageLuminanceSource` to switch between original formula & customized one🤔

**Comment by benjohnde** [comment]
I believe the best way to toggle that feature is to use `ZXDecodeHints` but I am not quite sure about how to inject the hint in `ZXCGImageLuminanceSource` tbh. Will think about that 🤔

**Comment by neacao** [comment]
How about define an enum for grayscale method inside `ZXDecodeHints`
Example:
```
typedef NS_ENUM(NSInteger, ZXLuminanceSourceType) {
 Normal,
 Luma, 
 Shades,
 ...
}
```

**Comment by benjohnde** [comment]
Good idea!

**Comment by neacao** [comment]
Instead of add to ZXLuminanceSource.h (from `core`), we can create new `ZXCGImageLuminanceSourceInfo` to handle this, so the `core` would not change but `client`

**Comment by benjohnde** [comment]
I like your implementation #446. Maybe one TestCase to roughly cover the branch of ZXCGImageLuminanceSourceShades and ZXCGImageLuminanceSourceDigital would be awesome. I am busy today, so I would merge this branch tomorrow after some testing session!

**Comment by neacao** [comment]
Sure, i will
