### ISSUE TITLE
Crash in ZXCapture.m

### ISSUE THREAD

**Issue by neacao** [TheLevelUp/ZXingObjC#431]
```
if (self.sessionPreset) {
  self.sessionPreset = AVCaptureSessionPreset1280x720;
}
self.session.sessionPreset = self.sessionPreset;
```
This will cause crash if sessionPresent is nil.

**Comment by benjohnde** [comment]
Ouch, ugly mistake :/ Thanks for fixing!

**Comment by benjohnde** [comment]
I just bumped the version to `3.4.1` and am currently pushing to CocoaPods. Should be available in minutes.
