### ISSUE TITLE
Incorrect capture's scanRect

### ISSUE THREAD

**Issue by neacao** [TheLevelUp/ZXingObjC#433]
Seems like `crop` before `rotate` will return wrong scan view frame, as you can see below, the second image show correct cropped area on the thumbnail view.

Crop then rotate
![img_0658](https://user-images.githubusercontent.com/16370568/46071121-88968600-c1a9-11e8-876c-8b1429e248e5.PNG)

Rotate then crop
![img_0657](https://user-images.githubusercontent.com/16370568/46071167-a663eb00-c1a9-11e8-88f7-4007bc051d3a.PNG)

**Comment by benjohnde** [comment]
Can you show me the code you are using to display the scanning rectangle?

I believe you are using `lastScannedImage`?

**Comment by neacao** [comment]
@benjohnde yes, i was displaying lastScannedImage, is it correct ?

**Comment by neacao** [comment]
Fore more information, both of `luminanceLayer` & my custom code return same result of incorrect scan rect

**Comment by benjohnde** [comment]
Yeah that is basically correct, weird.

I don't see a false note in the code.

In ZXCapture.m:

```objc
      // If scanRect is set, crop the current image to include only the desired rect
      if (!CGRectIsEmpty(self.scanRect)) {
        CGImageRef croppedImage = CGImageCreateWithImageInRect(videoFrameImage, self.scanRect);
        CGImageRelease(videoFrameImage);
        videoFrameImage = croppedImage;
      }
      
      CGImageRef rotatedImage = [self createRotatedImage:videoFrameImage degrees:self.rotation];
      CGImageRelease(videoFrameImage);
      self.lastScannedImage = rotatedImage;
```

**Comment by benjohnde** [comment]
Hmm you meam the small overlay (brighter area) does not match with the result thumbnail?

**Comment by benjohnde** [comment]
Because that is independent from ZXCapture.

**Comment by neacao** [comment]
That's true, the BarcodeScanner should to be updated, right ? :D

**Comment by benjohnde** [comment]
Yeap, but as the BarcodeScanner should be rewritten in Swift, I wont fix it as of now

**Comment by benjohnde** [comment]
You can give it a shot if you want to :)

**Comment by neacao** [comment]
@benjohnde to solve this one, the transformVideoRect have to be converted from portrait to landscape if needed. Sample code:
```
// Correct video frame under Portrait mode cuz the framework will crop before rotate
CGPoint scanPoint = CGPointMake(
  transformedVideoRect.origin.y, 
  self.view.frame.size.width - transformedVideoRect.size.width - transformedVideoRect.origin.x);

CGSize scanSize = CGSizeMake(
  transformedVideoRect.size.height, 
  transformedVideoRect.size.width);

transformedVideoRect = CGRectMake(scanPoint.x, scanPoint.y, scanSize.width, scanSize.height);
```

**Comment by benjohnde** [comment]
Do you want to hand-in a pull request? :)

**Comment by neacao** [comment]
Sure, I will

**Comment by neacao** [comment]
PR #444 is ready
