### ISSUE TITLE
The generated barcode is not readable

### ISSUE THREAD

**Issue by orkhanalizade** [TheLevelUp/ZXingObjC#435]
When I give a string to my method to generate DataMatrix from it, it generates but it seems in a wrong way, as I cannot read it later with the scanner. Also I've generated a new data matrix in some website and with your library, compared them and I see that they are not equal. I can scan the data matrix generated from that website but cannot do the same with the matrix generated with your library.

My code looks like: 

```
func generateDataMatrix(from xml: String) {
    let writer = ZXMultiFormatWriter()
    let result: ZXBitMatrix? = try? writer.encode(xml, format: kBarcodeFormatDataMatrix, width: Int32(barcodeImageView.frame.width), height: Int32(barcodeImageView.frame.height))
    if result != nil {
        let image: CGImage = ZXImage(matrix: result).cgimage

        barcodeImageView.image = UIImage(cgImage: image)
    }
}
```

Can you please help me with this problem? I do not know why generated matrix is NOT correct

**Comment by benjohnde** [comment]
Can you give an example string and maybe some additional information on the website you created the other candidate with?

You could also plain around with:

```
  ZXEncodeHints *hints = [ZXEncodeHints hints];
  hints.dataMatrixShape = ZXDataMatrixSymbolShapeHintForceSquare;
```

**Comment by orkhanalizade** [comment]
@benjohnde Hi, Ben. Thanks for your reply! Unfortunately it did not also help me.

My string is:

`<MP v=\"022\" U=\"C42FFB11DA74E035CC8C0\" l=\"de-DE\"><P g=\"Mich\" f=\"Must_1\" egk=\"M996218\" b=\"1926\" s=\"M\" /><A lanr=\"165630\" n=\"Drs. X Über\" s=\"Haupt 55\" z=\"01234\" c=\"Am\" p=\"04-12345\" e=\"m.uebl@mein-z.de\" t=\"01-04\" /><O w=\"89\" /><S c=\"412\"><M p=\"2262\" m=\"1\" /><M p=\"7020\" m=\"1\" /><M p=\"772\" t=\"mo:½-1 mi:(½-1)\" i=\"Hello, World\" /><M p=\"984\" v=\"1\" i=\"abds 1x1\" /></S><S c=\"418\"><M p=\"6360\" d=\"1\" /></S></MP>`

and the website where I generate data matrix from that string is: [https://barcode.tec-it.com/ru/DataMatrix?data=%3CMP%20v%3D%5C%22022%5C%22%20U%3D%5C%22C42FFB11DA74E035CC8C0%5C%22%20l%3D%5C%22de-DE%5C%22%3E%3CP%20g%3D%5C%22Mich%5C%22%20f%3D%5C%22Must_1%5C%22%20egk%3D%5C%22M996218%5C%22%20b%3D%5C%221926%5C%22%20s%3D%5C%22M%5C%22%20%2F%3E%3CA%20lanr%3D%5C%22165630%5C%22%20n%3D%5C%22Drs.%20X%20Über%5C%22%20s%3D%5C%22Haupt%2055%5C%22%20z%3D%5C%2201234%5C%22%20c%3D%5C%22Am%5C%22%20p%3D%5C%2204-12345%5C%22%20e%3D%5C%22m.uebl%40mein-z.de%5C%22%20t%3D%5C%2201-04%5C%22%20%2F%3E%3CO%20w%3D%5C%2289%5C%22%20%2F%3E%3CS%20c%3D%5C%22412%5C%22%3E%3CM%20p%3D%5C%222262%5C%22%20m%3D%5C%221%5C%22%20%2F%3E%3CM%20p%3D%5C%227020%5C%22%20m%3D%5C%221%5C%22%20%2F%3E%3CM%20p%3D%5C%22772%5C%22%20t%3D%5C%22mo%3A%C2%BD-1%20mi%3A(%C2%BD-1)%5C%22%20i%3D%5C%22Hello%2C%20World%5C%22%20%2F%3E%3CM%20p%3D%5C%22984%5C%22%20v%3D%5C%221%5C%22%20i%3D%5C%22abds%201x1%5C%22%20%2F%3E%3C%2FS%3E%3CS%20c%3D%5C%22418%5C%22%3E%3CM%20p%3D%5C%226360%5C%22%20d%3D%5C%221%5C%22%20%2F%3E%3C%2FS%3E%3C%2FMP%3E](url)

If you'll click on the link it will directly open the page with my text and generated data matrix. And if you'll compare the results then you'll see that they does not match

**Comment by benjohnde** [comment]
Maybe convert it with base64 or something like that? They seem to do at least something, because my Scandit app returns some hex code.

**Comment by orkhanalizade** [comment]
@benjohnde I'm not sure if I correctly understood you =/ I need convert string into an image, not vice versa. So did not get how Base64 can help me. Maybe I understood wrong

**Comment by benjohnde** [comment]
You could use something like https://stackoverflow.com/a/35360697 before you let the writer and then the reader do their work.

**Comment by orkhanalizade** [comment]
@benjohnde you mean my `xml` string to convert to Base64 or? I really do not understand what you mean, I’m really sorry. Maybe you could use my code and modify it or comment it? I know how to get Base64, I just do not understand from which value.
As I’m trying to convert my string, xml variable into matrix and do not understand where Base64 should help me

**Comment by orkhanalizade** [comment]
@benjohnde I have just got my text, converted it into Base64 and from Base64 text I've generated data matrix. But the same result there. Different data matrixes are being generated =/

**Comment by benjohnde** [comment]
@orkhanalizade yeah sorry, the Writer has a bug. If the text is longer than about 240 chars, the endresult is incorrect cf. #438.

**Comment by benjohnde** [comment]
Is fixed in the current HEAD. With Carthage you can directly start. I am pushing a new podspec to CocoaPods right now.
