### ISSUE TITLE
Scaling calculation might wrong

### ISSUE THREAD

**Issue by neacao** [TheLevelUp/ZXingObjC#449]
**BarcodeScanner.m**
The problem is when I change the `scanRectView` to another subview instead of `self.view`, the `scanRect` get wrong position to crop.

Currently there are:
```
...
videoSizeX = 1080;
videoSizeY = 1920;
...
scaleVideoX = self.view.frame.size.width / videoSizeX;
scaleVideoY = self.view.frame.size.height / videoSizeY;
```

As the code above, we calculate `scaleVideoX` & `scaleVideoY` based on `self.view.frame`. I think the `self.view.frame` should be `[UIScreen mainScreen].bounds` instead, cuz the scale have to be calculate on the screen instead of a view.

**Comment by neacao** [comment]
New PR will be available if this issue is correct 😀
@benjohnde FYI

**Comment by benjohnde** [comment]
In that particular case (of the example) you are right.

**Comment by benjohnde** [comment]
I will take a look at this potential bug tomorrow. I believe that the layout is not fully calculated which leads to wrong scaling. `self.view.frame.size` should be the same as as `UIScreen.main.bounds`.

**Comment by neacao** [comment]
@benjohnde the `self.view.frame.size` have been replaced by `self.capture.layer.frame` cuz the camera preview layer will take this frame instead.

**Comment by benjohnde** [comment]
Nice fix! Happy to review your PR :) Be aware of the indentation pls.

**Comment by neacao** [comment]
@benjohnde #450 FYI

**Comment by benjohnde** [comment]
Thanks again for your contribution!
