### ISSUE TITLE
chinese characters

### ISSUE THREAD

**Issue by GemstoneZheng** [TheLevelUp/ZXingObjC#462]
How to solve the problem of scanning random codes with Chinese characters? I set _hints.encoding = NSUTF8StringEncoding. But I did not solve How to solve the problem of scanning hints.encoding with Chinese characters. I have set _hints.encoding = NSUTF8StringEncoding But it didn't work

**Comment by benjohnde** [comment]
Have you tried something like that https://stackoverflow.com/a/14619359/5173688?

**Comment by benjohnde** [comment]
Could you provide some serious example? Then I could dive into your issue. Btw happy christmas :)

**Comment by GemstoneZheng** [comment]
Merry Christmas.Thank you very much for your answer.I tried to use the link you provided, but it didn't seem to work.
![image](https://user-images.githubusercontent.com/16421326/50408767-5936fa00-0828-11e9-9c97-f818f27bbc27.png)
The picture above is the one with this problem. The qrcode contains Chinese characters, and the string returned by ZXResult is garbled. It's my pleasure for your help.

**Comment by yuankaiJGH** [comment]
> Merry Christmas.Thank you very much for your answer.I tried to use the link you provided, but it didn't seem to work.
> ![image](https://user-images.githubusercontent.com/16421326/50408767-5936fa00-0828-11e9-9c97-f818f27bbc27.png)
> The picture above is the one with this problem. The qrcode contains Chinese characters, and the string returned by ZXResult is garbled. It's my pleasure for your help.

我也遇到了这个问题
GBK编码的中文会被优先转化为日文,修改ZXStringUtils对GBK编码的支持就可以了
    int length = bytes.length;
    BOOL canBeISO88591 = YES;
    BOOL canBeShiftJIS = YES;
    BOOL canBeUTF8 = YES;
    BOOL canBeGBK = YES;
    int utf8BytesLeft = 0;
    //int utf8LowChars = 0;
    int utf2BytesChars = 0;
    int utf3BytesChars = 0;
    int utf4BytesChars = 0;
    int sjisBytesLeft = 0;
    //int sjisLowChars = 0;
    int sjisKatakanaChars = 0;
    //int sjisDoubleBytesChars = 0;
    int sjisCurKatakanaWordLength = 0;
    int sjisCurDoubleBytesWordLength = 0;
    int sjisMaxKatakanaWordLength = 0;
    int sjisMaxDoubleBytesWordLength = 0;
    //int isoLowChars = 0;
    //int isoHighChars = 0;
    int isoHighOther = 0;
    
    BOOL utf8bom = length > 3 &&
    bytes.array[0] == (int8_t) 0xEF &&
    bytes.array[1] == (int8_t) 0xBB &&
    bytes.array[2] == (int8_t) 0xBF;
    
    for (int i = 0;
         i < length && (canBeISO88591 || canBeShiftJIS || canBeUTF8);
         i++) {
        
        int value = bytes.array[i] & 0xFF;
        
        // UTF-8 stuff
        if (canBeUTF8) {
            if (utf8BytesLeft > 0) {
                if ((value & 0x80) == 0) {
                    canBeUTF8 = NO;
                } else {
                    utf8BytesLeft--;
                }
            } else if ((value & 0x80) != 0) {
                if ((value & 0x40) == 0) {
                    canBeUTF8 = NO;
                } else {
                    utf8BytesLeft++;
                    if ((value & 0x20) == 0) {
                        utf2BytesChars++;
                    } else {
                        utf8BytesLeft++;
                        if ((value & 0x10) == 0) {
                            utf3BytesChars++;
                        } else {
                            utf8BytesLeft++;
                            if ((value & 0x08) == 0) {
                                utf4BytesChars++;
                            } else {
                                canBeUTF8 = NO;
                            }
                        }
                    }
                }
            } //else {
            //utf8LowChars++;
            //}
        }
        
        // ISO-8859-1 stuff
        if (canBeISO88591) {
            if (value > 0x7F && value < 0xA0) {
                canBeISO88591 = NO;
            } else if (value > 0x9F) {
                if (value < 0xC0 || value == 0xD7 || value == 0xF7) {
                    isoHighOther++;
                } //else {
                //isoHighChars++;
                //}
            } //else {
            //isoLowChars++;
            //}
        }
        
        if (canBeGBK) {
            // GBK stuff --
            int idx = 0;
            for (idx = 0; idx < length; idx++) {
                int val = bytes.array[idx], val2;
                if (val < 128)
                    continue;
                if (idx + 1 >= length)
                    break;
                val2 = bytes.array[idx+1];
                if (((val >= 0xA1 && val <= 0xA9) && (val2 >= 0xA1 && val2 <= 0xFE)) ||
                    ((val >= 0xB0 && val <= 0xF7) && (val2 >= 0xA1 && val2 <= 0xFE)) ||
                    ((val >= 0x81 && val <= 0xA0) && (val2 >= 0x40 && val2 <= 0xFE && val2 != 0x7F)) ||
                    ((val >= 0xAA && val <= 0xFE) && (val2 >= 0x40 && val2 <= 0xA0 && val2 != 0x7F)) ||
                    ((val >= 0xA8 && val <= 0xA9) && (val2 >= 0x40 && val2 <= 0xA0 && val2 != 0x7F)) ||
                    ((val >= 0xAA && val <= 0xAF) && (val2 >= 0xA1 && val2 <= 0xFE)) ||
                    ((val >= 0xF8 && val <= 0xFE) && (val2 >= 0xA1 && val2 <= 0xFE)) ||
                    ((val >= 0xA1 && val <= 0xA7) && (val2 >= 0x40 && val2 <= 0xA0 && val2 != 0x7F))) {
                    idx++;
                } else {
                    break;
                }
            }
            
            if (idx != length) {
                canBeGBK = NO;
            }
            
            // GBK stuff end
            
        }
        
        // Shift_JIS stuff
        if (canBeShiftJIS) {
            if (sjisBytesLeft > 0) {
                if (value < 0x40 || value == 0x7F || value > 0xFC) {
                    canBeShiftJIS = NO;
                } else {
                    sjisBytesLeft--;
                }
            } else if (value == 0x80 || value == 0xA0 || value > 0xEF) {
                canBeShiftJIS = NO;
            } else if (value > 0xA0 && value < 0xE0) {
                sjisKatakanaChars++;
                sjisCurDoubleBytesWordLength = 0;
                sjisCurKatakanaWordLength++;
                if (sjisCurKatakanaWordLength > sjisMaxKatakanaWordLength) {
                    sjisMaxKatakanaWordLength = sjisCurKatakanaWordLength;
                }
            } else if (value > 0x7F) {
                sjisBytesLeft++;
                //sjisDoubleBytesChars++;
                sjisCurKatakanaWordLength = 0;
                sjisCurDoubleBytesWordLength++;
                if (sjisCurDoubleBytesWordLength > sjisMaxDoubleBytesWordLength) {
                    sjisMaxDoubleBytesWordLength = sjisCurDoubleBytesWordLength;
                }
            } else {
                //sjisLowChars++;
                sjisCurKatakanaWordLength = 0;
                sjisCurDoubleBytesWordLength = 0;
            }
        }
    }
    
    if (canBeUTF8 && utf8BytesLeft > 0) {
        canBeUTF8 = NO;
    }
    if (canBeShiftJIS && sjisBytesLeft > 0) {
        canBeShiftJIS = NO;
    }
    
    if (canBeGBK) {
        NSStringEncoding enc = CFStringConvertEncodingToNSStringEncoding(kCFStringEncodingGB_18030_2000);
        return enc;
    }

**Comment by GemstoneZheng** [comment]
蟹蟹 感谢！学习了！ @yuankaiJGH
